// levels.test.js — the C34 level-campaign gate (KANBAN C34; engine-side
// node --test, NOT a DOM-glue exception: it drives the level definitions
// against engine truth the way pio-asm-golden.json anchors the assembler).
//
// The engine truth arrives as committed golden pin series
// (web/tests/levels-golden.json, regenerated by tools/gen_level_goldens.py
// from pio_model — the same oracle make web's client gate runs against,
// bit-equal to the RTL). Every level under web/levels/ must:
//
//   - register a complete definition (id/name/chapter/goal, program,
//     panels, opcodes, profile, predict, reference+par) and assemble to
//     words bit-equal with pio_model's own assembler (the golden's words);
//   - carry only canonical listing rows (assemble∘disassemble = identity,
//     the C32 discipline) and an SM overlay that survives the C22
//     compose/decompose round-trip;
//   - PASS its own monitor profile over the reference golden series and
//     go RED over every perturbed golden (a judge that accepts the
//     perturbed waves is a lens pretending to be a judge);
//   - lock the transport behind the predict gate until a prediction is
//     committed — and never re-lock a re-run (the 2026-09-04 owner
//     decision: first run of a non-authored program only).
//
// The two standing defect hooks run their red/green demonstration
// in-process here (the TestMutationsDiverge idiom): {defect:'judge'}
// re-injects the single-glitch pass (stability ignored) and
// {defect:'gate'} re-injects the never-locks gate; the suite asserts the
// clean module is green AND that the very same checks diverge on the
// defective one.

'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const PioLevels = require('../levels.js');
const PioAsm = require('../pio-asm.js');
const VibeDriver = require('../engine-driver.js');
const GOLDEN = JSON.parse(fs.readFileSync(path.join(__dirname, 'levels-golden.json'), 'utf8'));

// the shipped level files register through the same hook the browser's
// classic scripts call (levels.js defines PIO_LEVEL; the loader document
// -writes the level file before sm-view.js evaluates)
globalThis.PIO_LEVEL = PioLevels.register;
require('../levels/l0.js');

const L0 = PioLevels.get('l0');
const G0 = GOLDEN.levels.l0;
const bits = (s) => [...s].map(Number);
const case_ = (name) => {
  const c = G0.cases.find((c) => c.name === name);
  assert.ok(c, `golden case ${name} exists`);
  return c;
};

// ---- the definition is complete and self-consistent ----------------------
test('l0 registers complete: identity, program, surface, profile, predict, par', () => {
  assert.equal(L0.id, 'l0');
  assert.equal(L0.name, 'First light');
  assert.equal(L0.chapter, 0);
  assert.equal(typeof L0.goal, 'string');
  assert.ok(L0.goal.length > 8, 'the goal is subgoal phrasing, not a letter');
  assert.ok(Array.isArray(L0.program.listing) && L0.program.listing.length > 0);
  assert.ok(Array.isArray(L0.program.sms) && L0.program.sms.length === 4);
  // the page IS the knowledge state: L0 shows transport+listing+wave only
  for (const key of ['transport', 'listing', 'wave']) assert.ok(L0.panels.includes(key));
  // no authoring in chapter 0 L0: the row-editor whitelist is empty
  assert.deepEqual(L0.opcodes, []);
  // the profile is versioned and tiered (the ladder's skeleton, C35 grows it)
  assert.equal(L0.profile.kind, 'square');
  assert.equal(L0.profile.v, 1);
  assert.ok(L0.profile.tiers[L0.profile.tier], 'the active tier is defined');
  // the predict gate: an answer that names one of the candidates
  assert.ok(L0.predict.candidates.some((c) => c.id === L0.predict.answer));
  assert.ok(L0.predict.candidates.every((c) => /^[01]+$/.test(c.bits)));
  assert.ok(L0.reference.par.words > 0 && L0.reference.par.period > 0);
});

test('every surface key maps to selectors that exist in the shipped page', () => {
  const html = fs.readFileSync(path.join(__dirname, '..', 'sm-view.html'), 'utf8');
  for (const [key, sels] of Object.entries(PioLevels.SURFACE)) {
    for (const sel of sels) {
      const m = sel.match(/^[.#]([A-Za-z0-9_-]+)$/);
      assert.ok(m, `surface ${key}: selector ${sel} must be one id/class`);
      const present = sel[0] === '#' ? html.includes(`id="${m[1]}"`) : html.includes(`${m[1]}`);
      assert.ok(present, `surface ${key}: ${sel} not found in sm-view.html`);
    }
  }
});

// ---- the program: canonical rows, pio_model-equal words, C22 overlay ------
test('l0 rows are canonical spellings: assemble(disassemble(w)) === w === the row', () => {
  const prog = PioAsm.createProgram('l0-check');
  prog.sidesetBits = 0; // no side-set in L0 (all five ds bits are delay)
  L0.program.listing.forEach((row) => {
    const w = PioAsm.assembleInstruction(row, prog, {}, `l0 row ${row}`);
    assert.equal(PioAsm.disassemble(w, false, 0), row, `${row} is not the canonical spelling`);
  });
});

test('l0 assembles to words bit-equal with the pio_model golden', () => {
  const st = PioLevels.programState(L0, PioAsm, VibeDriver);
  assert.deepEqual(st.words, G0.words);
  // a stored-program state the driver accepts as-is (parseState already ran)
  assert.equal(st.words.length, 32);
  assert.ok(
    st.words.slice(2).every((w) => w === 0),
    '32 rows, honest from cycle one',
  );
});

test('l0 SM overlay round-trips the C22 compose/decompose', () => {
  const st = PioLevels.programState(L0, PioAsm, VibeDriver);
  for (const group of ['clkdiv', 'pinctrl', 'execctrl', 'shiftctrl']) {
    const word = VibeDriver.composeOverlay(group, st.sms[0][group]);
    const back = VibeDriver.decomposeOverlay(group, word);
    for (const [field, v] of Object.entries(st.sms[0][group]))
      assert.deepEqual(back[field], v, `${group}.${field} survives compose∘decompose`);
    // the composed words equal the oracle's stim builders over the same
    // merged overlay (per SM — the disabled SMs compose their reset words)
    const gi = { pinctrl: 0, execctrl: 1, shiftctrl: 2, clkdiv: 3 }[group];
    for (let i = 0; i < 4; i++) {
      assert.equal(
        VibeDriver.composeOverlay(group, st.sms[i][group]),
        G0.config[i][gi],
        `SM${i} ${group} composes to the oracle word`,
      );
    }
  }
});

// ---- the judge: reference green, perturbed red ---------------------------
test('the square judge passes the reference golden — full series and windowed', () => {
  const ref = case_('reference');
  const full = PioLevels.judge(bits(ref.series), L0.profile);
  assert.equal(full.pass, true, full.verdict);
  assert.equal(full.period, 2); // set pins,1 / set pins,0: one clk each
  assert.equal(full.dutyPct, 50);
  // the browser judges the wave window (the driver's last-128 samples):
  // the verdict must not depend on where the window sits
  const win = PioLevels.judge(bits(ref.series).slice(-128), L0.profile);
  assert.equal(win.pass, true, win.verdict);
});

test('the square judge reds every perturbed golden, legibly', () => {
  for (const name of ['both-high', 'one-row', 'flat-low']) {
    const c = case_(name);
    const v = PioLevels.judge(bits(c.series), L0.profile);
    assert.equal(v.pass, false, `${name} must not pass its monitor profile`);
    assert.ok(v.verdict.length > 8, `${name} fails with a reason, not silence`);
  }
  // legibility spot-checks: the flat wave says the pin never rose
  assert.match(PioLevels.judge(bits(case_('flat-low').series), L0.profile).verdict, /never rose/);
});

test('{defect:judge} re-injects the single-glitch pass — clean red, defect green', () => {
  // one clean period, then the wave goes flat high: the clean judge needs
  // minPeriods steady cycles and stays red; the defect passes any single
  // in-range period (the lens masquerading as a judge)
  const blip = [0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1];
  const clean = PioLevels.judge(blip, L0.profile);
  const buggy = PioLevels.judge(blip, L0.profile, { judge: true });
  assert.equal(clean.pass, false, 'the clean judge refuses a one-period blip');
  assert.equal(buggy.pass, true, 'the defect hook passes it — divergence demonstrated');
  // and the clean judge still passes the real reference (green side)
  assert.equal(PioLevels.judge(bits(case_('reference').series), L0.profile).pass, true);
});

// ---- the predict gate ------------------------------------------------------
test('the gate locks the first run and never re-locks a re-run', () => {
  assert.equal(PioLevels.gateOpen(L0, {}), false, 'locked at boot: nothing predicted yet');
  assert.equal(PioLevels.gateOpen(L0, { predicted: true }), true, 'a commit opens it');
  // a reset re-runs the same program: the gate stays open (never punish
  // re-runs — the 2026-09-04 owner decision)
  assert.equal(PioLevels.gateOpen(L0, { predicted: true, solved: true }), true);
  // a level without a predict field (authored programs, later chapters)
  // never locks
  assert.equal(PioLevels.gateOpen({ ...L0, predict: null }, {}), true);
});

test('{defect:gate} re-injects the never-locks gate — divergence demonstrated', () => {
  const buggy = PioLevels.gateOpen(L0, {}, { gate: true });
  assert.equal(buggy, true, 'the defect ships the gate open');
  assert.equal(PioLevels.gateOpen(L0, {}), false, 'the clean gate locks at boot');
});

// ---- par dominates the reference on both axes ------------------------------
test('par dominates the reference solution on both axes', () => {
  const used = G0.words.filter((w) => w !== 0).length;
  assert.ok(used <= L0.reference.par.words, `${used} words > par ${L0.reference.par.words}`);
  const v = PioLevels.judge(bits(case_('reference').series), L0.profile);
  assert.ok(v.period <= L0.reference.par.period, `${v.period} clk/cycle > par period`);
});
