// levels.test.js — the C34/C35 level-campaign gate (engine-side
// node --test, NOT a DOM-glue exception: it drives the level definitions
// against engine truth the way pio-asm-golden.json anchors the assembler).
//
// The engine truth arrives as committed golden pin series
// (web/tests/levels-golden.json, regenerated by tools/gen_level_goldens.py
// from pio_model — the same oracle make web's client gate runs against,
// bit-equal to the RTL). Every level under web/levels/ must:
//
//   - register a complete definition (id/name/chapter/goal, program,
//     panels, opcodes, profile, predict, reference+par) and assemble to
//     words bit-equal with pio_model's own assembler (the golden's words);
//   - carry only canonical listing rows (assemble∘disassemble = identity,
//     the C32 discipline) and an SM overlay that survives the C22
//     compose/decompose round-trip;
//   - PASS its own monitor profile over the reference golden series and
//     go RED over every perturbed golden (a judge that accepts the
//     perturbed waves is a lens pretending to be a judge);
//   - lock the transport behind the predict gate until a prediction is
//     committed — and never re-lock a re-run (the 2026-09-04 owner
//     decision: first run of a non-authored program only).
//
// The two standing defect hooks run their red/green demonstration
// in-process here (the TestMutationsDiverge idiom): {defect:'judge'}
// re-injects the single-glitch pass (stability ignored) and
// {defect:'gate'} re-injects the never-locks gate; the suite asserts the
// clean module is green AND that the very same checks diverge on the
// defective one.

'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const PioLevels = require('../levels.js');
const PioAsm = require('../pio-asm.js');
const VibeDriver = require('../engine-driver.js');
const GOLDEN = JSON.parse(fs.readFileSync(path.join(__dirname, 'levels-golden.json'), 'utf8'));

// the shipped level files register through the same hook the browser's
// classic scripts call (levels.js defines PIO_LEVEL; the loader document
// -writes the level file before sm-view.js evaluates)
globalThis.PIO_LEVEL = PioLevels.register;
require('../levels/l0.js');
require('../levels/l1.js');
require('../levels/l2.js');

const L0 = PioLevels.get('l0');
const G0 = GOLDEN.levels.l0;
const L1 = PioLevels.get('l1');
const G1 = GOLDEN.levels.l1;
const L2 = PioLevels.get('l2');
const G2 = GOLDEN.levels.l2;
const RowComplete = require('../row-complete.js');
const bits = (s) => [...s].map(Number);
const case_ = (name) => {
  const c = G0.cases.find((c) => c.name === name);
  assert.ok(c, `golden case ${name} exists`);
  return c;
};
const caseOf = (g, name) => {
  const c = g.cases.find((c) => c.name === name);
  assert.ok(c, `golden case ${name} exists`);
  return c;
};

// ---- the definition is complete and self-consistent ----------------------
test('l0 registers complete: identity, program, surface, profile, predict, par', () => {
  assert.equal(L0.id, 'l0');
  assert.equal(L0.name, 'First light');
  assert.equal(L0.chapter, 0);
  assert.equal(typeof L0.goal, 'string');
  assert.ok(L0.goal.length > 8, 'the goal is subgoal phrasing, not a letter');
  assert.ok(Array.isArray(L0.program.listing) && L0.program.listing.length > 0);
  assert.ok(Array.isArray(L0.program.sms) && L0.program.sms.length === 4);
  // the page IS the knowledge state: L0 shows transport+listing+wave only
  for (const key of ['transport', 'listing', 'wave']) assert.ok(L0.panels.includes(key));
  // no authoring in chapter 0 L0: the row-editor whitelist is empty
  assert.deepEqual(L0.opcodes, []);
  // the profile is versioned and tiered (the ladder's skeleton, C35 grows it)
  assert.equal(L0.profile.kind, 'square');
  assert.equal(L0.profile.v, 1);
  assert.ok(L0.profile.tiers[L0.profile.tier], 'the active tier is defined');
  // the predict gate: an answer that names one of the candidates
  assert.ok(L0.predict.candidates.some((c) => c.id === L0.predict.answer));
  assert.ok(L0.predict.candidates.every((c) => /^[01]+$/.test(c.bits)));
  assert.ok(L0.reference.par.words > 0 && L0.reference.par.period > 0);
});

test('every surface key maps to selectors that exist in the shipped page', () => {
  const html = fs.readFileSync(path.join(__dirname, '..', 'sm-view.html'), 'utf8');
  for (const [key, sels] of Object.entries(PioLevels.SURFACE)) {
    for (const sel of sels) {
      const m = sel.match(/^[.#]([A-Za-z0-9_-]+)$/);
      assert.ok(m, `surface ${key}: selector ${sel} must be one id/class`);
      const present = sel[0] === '#' ? html.includes(`id="${m[1]}"`) : html.includes(`${m[1]}`);
      assert.ok(present, `surface ${key}: ${sel} not found in sm-view.html`);
    }
  }
});

// ---- the program: canonical rows, pio_model-equal words, C22 overlay ------
test('l0 rows are canonical spellings: assemble(disassemble(w)) === w === the row', () => {
  const prog = PioAsm.createProgram('l0-check');
  prog.sidesetBits = 0; // no side-set in L0 (all five ds bits are delay)
  L0.program.listing.forEach((row) => {
    const w = PioAsm.assembleInstruction(row, prog, {}, `l0 row ${row}`);
    assert.equal(PioAsm.disassemble(w, false, 0), row, `${row} is not the canonical spelling`);
  });
});

test('l0 assembles to words bit-equal with the pio_model golden', () => {
  const st = PioLevels.programState(L0, PioAsm, VibeDriver);
  assert.deepEqual(st.words, G0.words);
  // a stored-program state the driver accepts as-is (parseState already ran)
  assert.equal(st.words.length, 32);
  assert.ok(
    st.words.slice(2).every((w) => w === 0),
    '32 rows, honest from cycle one',
  );
});

test('l0 SM overlay round-trips the C22 compose/decompose', () => {
  const st = PioLevels.programState(L0, PioAsm, VibeDriver);
  for (const group of ['clkdiv', 'pinctrl', 'execctrl', 'shiftctrl']) {
    const word = VibeDriver.composeOverlay(group, st.sms[0][group]);
    const back = VibeDriver.decomposeOverlay(group, word);
    for (const [field, v] of Object.entries(st.sms[0][group]))
      assert.deepEqual(back[field], v, `${group}.${field} survives compose∘decompose`);
    // the composed words equal the oracle's stim builders over the same
    // merged overlay (per SM — the disabled SMs compose their reset words)
    const gi = { pinctrl: 0, execctrl: 1, shiftctrl: 2, clkdiv: 3 }[group];
    for (let i = 0; i < 4; i++) {
      assert.equal(
        VibeDriver.composeOverlay(group, st.sms[i][group]),
        G0.config[i][gi],
        `SM${i} ${group} composes to the oracle word`,
      );
    }
  }
});

// ---- the judge: reference green, perturbed red ---------------------------
test('the square judge passes the reference golden — full series and windowed', () => {
  const ref = case_('reference');
  const full = PioLevels.judge(bits(ref.series), L0.profile);
  assert.equal(full.pass, true, full.verdict);
  assert.equal(full.period, 2); // set pins,1 / set pins,0: one clk each
  assert.equal(full.dutyPct, 50);
  // the browser judges the wave window (the driver's last-128 samples):
  // the verdict must not depend on where the window sits
  const win = PioLevels.judge(bits(ref.series).slice(-128), L0.profile);
  assert.equal(win.pass, true, win.verdict);
});

test('the square judge reds every perturbed golden, legibly', () => {
  for (const name of ['both-high', 'one-row', 'flat-low']) {
    const c = case_(name);
    const v = PioLevels.judge(bits(c.series), L0.profile);
    assert.equal(v.pass, false, `${name} must not pass its monitor profile`);
    assert.ok(v.verdict.length > 8, `${name} fails with a reason, not silence`);
  }
  // legibility spot-checks: the flat wave says the pin never rose
  assert.match(PioLevels.judge(bits(case_('flat-low').series), L0.profile).verdict, /never rose/);
});

test('{defect:judge} re-injects the single-glitch pass — clean red, defect green', () => {
  // one clean period, then the wave goes flat high: the clean judge needs
  // minPeriods steady cycles and stays red; the defect passes any single
  // in-range period (the lens masquerading as a judge)
  const blip = [0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1];
  const clean = PioLevels.judge(blip, L0.profile);
  const buggy = PioLevels.judge(blip, L0.profile, { judge: true });
  assert.equal(clean.pass, false, 'the clean judge refuses a one-period blip');
  assert.equal(buggy.pass, true, 'the defect hook passes it — divergence demonstrated');
  // and the clean judge still passes the real reference (green side)
  assert.equal(PioLevels.judge(bits(case_('reference').series), L0.profile).pass, true);
});

// ---- the predict gate ------------------------------------------------------
test('the gate locks the first run and never re-locks a re-run', () => {
  assert.equal(PioLevels.gateOpen(L0, {}), false, 'locked at boot: nothing predicted yet');
  assert.equal(PioLevels.gateOpen(L0, { predicted: true }), true, 'a commit opens it');
  // a reset re-runs the same program: the gate stays open (never punish
  // re-runs — the 2026-09-04 owner decision)
  assert.equal(PioLevels.gateOpen(L0, { predicted: true, solved: true }), true);
  // a level without a predict field (authored programs, later chapters)
  // never locks
  assert.equal(PioLevels.gateOpen({ ...L0, predict: null }, {}), true);
});

test('{defect:gate} re-injects the never-locks gate — divergence demonstrated', () => {
  const buggy = PioLevels.gateOpen(L0, {}, { gate: true });
  assert.equal(buggy, true, 'the defect ships the gate open');
  assert.equal(PioLevels.gateOpen(L0, {}), false, 'the clean gate locks at boot');
});

// ---- par dominates the reference on both axes ------------------------------
test('par dominates the reference solution on both axes', () => {
  const used = G0.words.filter((w) => w !== 0).length;
  assert.ok(used <= L0.reference.par.words, `${used} words > par ${L0.reference.par.words}`);
  const v = PioLevels.judge(bits(case_('reference').series), L0.profile);
  assert.ok(v.period <= L0.reference.par.period, `${v.period} clk/cycle > par period`);
});

// ---- C35: L1 Metronome — the delay column, the timing profile ---------------
// The fade's first rung: a one-cell modification. The program arrives as
// L0 left it; the monitor now TIMES it (the profile ladder's first real
// tier — exact period); the reference solution ships separately from the
// boot program for the first time.
test('l1 registers complete: delay column unlocked, exact-time profile, no gate', () => {
  assert.equal(L1.id, 'l1');
  assert.equal(L1.name, 'Metronome');
  assert.equal(L1.chapter, 0);
  assert.ok(L1.goal.length > 8);
  assert.ok(L1.panels.includes('delayCol'), "the delay column is L1's debut");
  assert.ok(!L1.panels.includes('sideCol'), 'no side column until chapter 4');
  // no authoring yet: the delay cell is the whole editor (the row editor
  // opens in a level for the first time in L2)
  assert.deepEqual(L1.opcodes, []);
  // the timing monitor is born: the active tier demands the exact period
  assert.equal(L1.profile.v, 1);
  assert.equal(L1.profile.tier, 'exact');
  assert.equal(L1.profile.tiers.exact.periodLo, 8);
  assert.equal(L1.profile.tiers.exact.periodHi, 8);
  // modify-from-given levels never lock the gate (only predict levels do)
  assert.equal(PioLevels.gateOpen(L1, {}), true);
  // the shipped answer, separate from the boot program
  assert.deepEqual(L1.reference.listing, ['set pins, 1 [3]', 'set pins, 0 [3]']);
  assert.ok(L1.reference.par.words > 0 && L1.reference.par.period > 0);
});

test('l2 registers complete: the empty boot, the set leash, the 1:3 target', () => {
  assert.equal(L2.id, 'l2');
  assert.equal(L2.name, "Author's hand");
  assert.equal(L2.chapter, 0);
  assert.ok(L2.goal.length > 8);
  // from scratch: the listing boots EMPTY — row-count honesty means the
  // player sees 32 honest `·` rows and writes into them
  assert.deepEqual(L2.program.listing, []);
  assert.ok(L2.panels.includes('delayCol'), 'the delay cell stays in scope');
  assert.ok(!L2.panels.includes('sideCol'), 'no side column until chapter 4');
  // the row editor opens in a level for the first time — on the leash
  assert.deepEqual(L2.opcodes, ['set']);
  assert.equal(L2.profile.v, 1);
  assert.equal(L2.profile.tier, 'exact');
  assert.equal(L2.profile.tiers.exact.periodLo, 4);
  assert.equal(L2.profile.tiers.exact.periodHi, 4);
  // the player authored the program from the first keystroke: no gate
  assert.equal(PioLevels.gateOpen(L2, {}), true);
  assert.deepEqual(L2.reference.listing, ['set pins, 1', 'set pins, 0 [2]']);
  assert.ok(L2.reference.par.words > 0 && L2.reference.par.period > 0);
});

test('l1/l2 reference listings are canonical spellings', () => {
  const prog = PioAsm.createProgram('c35-check');
  prog.sidesetBits = 0; // no side-set in chapter 0 (all five ds bits are delay)
  for (const L of [L1, L2])
    for (const row of L.reference.listing) {
      const w = PioAsm.assembleInstruction(row, prog, {}, `${L.id} reference ${row}`);
      assert.equal(PioAsm.disassemble(w, false, 0), row, `${row} is not the canonical spelling`);
    }
});

test('l1/l2 references assemble bit-equal with pio_model; the boots are their own words', () => {
  const prog = PioAsm.createProgram('c35-words');
  prog.sidesetBits = 0;
  for (const [L, G] of [
    [L1, G1],
    [L2, G2],
  ]) {
    const words = new Array(32).fill(0);
    L.reference.listing.forEach((row, i) => {
      words[i] = PioAsm.assembleInstruction(row, prog, {}, `${L.id} ref row ${i}`);
    });
    assert.deepEqual(words, G.words, `${L.id}: the JS assembler drifted from pio_model`);
    // the boot program is what the page loads (programState), and the
    // golden carries it separately whenever it differs from the reference
    const st = PioLevels.programState(L, PioAsm, VibeDriver);
    if (L.program.listing.join('|') !== L.reference.listing.join('|')) {
      assert.ok(G.boot, `${L.id}: the boot case is committed`);
      assert.deepEqual(st.words, G.boot.words, `${L.id}: the page boots the golden's boot words`);
    } else {
      assert.deepEqual(st.words, G.words);
    }
  }
  // L2 boots the empty machine: 32 untouched slots
  assert.ok(PioLevels.programState(L2, PioAsm, VibeDriver).words.every((w) => w === 0));
});

test('the metronome: the reference keeps exact time, every wrong time reds', () => {
  const ref = caseOf(G1, 'reference');
  const full = PioLevels.judge(bits(ref.series), L1.profile);
  assert.equal(full.pass, true, full.verdict);
  assert.equal(full.period, 8);
  assert.equal(full.dutyPct, 50);
  const win = PioLevels.judge(bits(ref.series).slice(-128), L1.profile);
  assert.equal(win.pass, true, win.verdict);
  // the boot program (as L0 left it) reds: the task is real from cycle one
  const boot = PioLevels.judge(bits(G1.boot.series), L1.profile);
  assert.equal(boot.pass, false);
  assert.match(boot.verdict, /outside/, 'the boot flash is timed, and legibly');
  // the wrong answers red with reasons
  for (const name of ['too-slow', 'lopsided', 'one-row']) {
    const c = caseOf(G1, name);
    const v = PioLevels.judge(bits(c.series), L1.profile);
    assert.equal(v.pass, false, `${name} must not pass the metronome`);
    assert.ok(v.verdict.length > 8, `${name} fails with a reason, not silence`);
  }
  // the near-miss is legible as a DUTY failure: period 8, duty 25
  assert.match(PioLevels.judge(bits(caseOf(G1, 'lopsided').series), L1.profile).verdict, /duty/);
});

test("the 1:3 target: the reference passes, last level's answer and the boot red", () => {
  const ref = caseOf(G2, 'reference');
  const full = PioLevels.judge(bits(ref.series), L2.profile);
  assert.equal(full.pass, true, full.verdict);
  assert.equal(full.period, 4);
  assert.equal(full.dutyPct, 25);
  assert.equal(PioLevels.judge(bits(ref.series).slice(-128), L2.profile).pass, true);
  // L1's solution is this level's red case: the target moved
  const l1a = PioLevels.judge(bits(caseOf(G2, 'l1-answer').series), L2.profile);
  assert.equal(l1a.pass, false);
  assert.match(l1a.verdict, /period/);
  // the opcode-locked attempt: nop cannot bring the pin low — the wave
  // rises once and holds
  const nop = PioLevels.judge(bits(caseOf(G2, 'nop-wait').series), L2.profile);
  assert.equal(nop.pass, false, 'the locked-opcode variant must not pass');
  // the empty boot never rises
  const boot = PioLevels.judge(bits(G2.boot.series), L2.profile);
  assert.equal(boot.pass, false);
  assert.match(boot.verdict, /never rose/);
});

// ---- C35: the editor's leash (the completion whitelist) ----------------------
// The row editor opens in a level for the first time in L2, scoped to the
// unlocked opcode set: a filter over C32's slot-aware candidates. The
// menu never suggests what the level has not unlocked — not at the
// mnemonic slot, and not inside a locked mnemonic's operand slots.
test('the leash: L2 completions scope to the unlocked opcode set', () => {
  const wl = { opcodes: L2.opcodes };
  assert.deepEqual(
    RowComplete.analyze('', wl).cands.map((c) => c.t),
    ['set'],
    'the mnemonic menu offers exactly the unlocked set',
  );
  assert.deepEqual(
    RowComplete.analyze('mo', wl).cands,
    [],
    'a locked mnemonic mid-word is never suggested',
  );
  assert.deepEqual(
    RowComplete.analyze('mov x', wl).cands,
    [],
    "a locked mnemonic's operand slots stay silent",
  );
  assert.deepEqual(
    RowComplete.analyze('', { opcodes: [] }).cands,
    [],
    "an empty whitelist offers nothing at all (L0's world)",
  );
  // the filter is load-bearing: unscoped, the menu offers all ten
  assert.deepEqual(
    RowComplete.analyze('').cands.map((c) => c.t),
    ['jmp', 'wait', 'in', 'out', 'push', 'pull', 'mov', 'irq', 'set', 'nop'],
  );
  // and the leash never touches the sandbox: no whitelist, full menu —
  // including set's own operand slots inside the whitelist
  assert.ok(RowComplete.analyze('set ', wl).cands.some((c) => c.t === 'pins'));
});

test('par dominates the l1/l2 reference solutions on both axes', () => {
  for (const [L, G] of [
    [L1, G1],
    [L2, G2],
  ]) {
    const used = G.words.filter((w) => w !== 0).length;
    assert.ok(used <= L.reference.par.words, `${L.id}: ${used} words > par`);
    const v = PioLevels.judge(bits(G.cases[0].series), L.profile);
    assert.ok(v.period <= L.reference.par.period, `${L.id}: ${v.period} clk/cycle > par`);
  }
});

// ---- C36: L3 Two ways to loop — jmp debuts with a job ----------------------
// Chapter 1 opens: a task wrap cannot do. The boot ships L2's answer
// transplanted after a once-preamble (row 0), and the pinned wrap
// (0..3) loops the WHOLE listing — the flash comes round every period,
// the exact tier reds it, and the only way out is a jmp back edge that
// skips row 0. The cost lesson is a golden: the naive jmp port of L2's
// rows runs one clk slower (period 5) — jmp eats a slot AND a cycle,
// wrap eats neither (the par line says 4 words · 4 clk; L2's par said
// the same wave in 2 words · 4 clk with no back-edge clk at all).
require('../levels/l3.js');
const L3 = PioLevels.get('l3');
const G3 = GOLDEN.levels.l3;

test('l3 registers complete: chapter 1, jmp on the leash, no gate', () => {
  assert.equal(L3.id, 'l3');
  assert.equal(L3.name, 'Two ways to loop');
  assert.equal(L3.chapter, 1);
  assert.ok(L3.goal.length > 8);
  // the boot: L2's answer after a once-preamble, wrap over the listing
  assert.deepEqual(L3.program.listing, ['set pins, 1 [7]', 'set pins, 1', 'set pins, 0 [2]']);
  assert.equal(L3.program.sms[0].execctrl.wrapTop, 3);
  assert.equal(L3.program.sms[0].execctrl.wrapBot, 0);
  assert.ok(L3.panels.includes('delayCol'), 'the delay cell stays in scope');
  assert.ok(!L3.panels.includes('sideCol'), 'no side column until chapter 4');
  assert.ok(!L3.panels.includes('wrapSteppers'), 'the wrap steppers stay locked');
  // the leash grows its first structural opcode: set + jmp, exactly
  assert.deepEqual(L3.opcodes, ['set', 'jmp']);
  // the same steady wave as L2 (the 1:3), judged at the exact tier
  assert.equal(L3.profile.v, 1);
  assert.equal(L3.profile.tier, 'exact');
  assert.equal(L3.profile.tiers.exact.periodLo, 4);
  assert.equal(L3.profile.tiers.exact.periodHi, 4);
  // modify-from-given: no predict card, the gate never locks
  assert.equal(PioLevels.gateOpen(L3, {}), true);
  // the shipped answer: preamble kept, jmp back edge, one delay shaved
  assert.deepEqual(L3.reference.listing, [
    'set pins, 1 [7]',
    'set pins, 1',
    'set pins, 0 [1]',
    'jmp 1',
  ]);
  assert.deepEqual(L3.reference.par, { words: 4, period: 4 });
});

test('the l3 leash: the menu offers set and jmp — the chapter-1 vocabulary', () => {
  const wl = { opcodes: L3.opcodes };
  assert.deepEqual(
    RowComplete.analyze('', wl).cands.map((c) => c.t),
    ['jmp', 'set'],
    'the mnemonic menu offers exactly the unlocked set (jmp first — the C32 order)',
  );
  // jmp's own slots stay live under the leash: digits are the target
  assert.ok(RowComplete.analyze('jm', wl).cands.some((c) => c.t === 'jmp'));
  assert.ok(RowComplete.analyze('jmp ', wl).cands.length >= 0, "jmp's target slot stays in play");
  // the still-locked majority stays silent
  assert.deepEqual(RowComplete.analyze('wa', wl).cands, []);
  assert.deepEqual(RowComplete.analyze('pull', wl).cands, []);
});

test('the l3 wave contract: boot reds (the wrap cannot skip row 0), reference greens', () => {
  // the boot: the whole-listing wrap re-runs the preamble — one long
  // flash every 13 clk, legibly outside the 4-clk window
  const boot = PioLevels.judge(bits(G3.boot.series), L3.profile);
  assert.equal(boot.pass, false);
  assert.match(boot.verdict, /period 13 .*outside/);
  // the reference: the steady 1:3 — full series and the wave window
  const ref = caseOf(G3, 'reference');
  const full = PioLevels.judge(bits(ref.series), L3.profile);
  assert.equal(full.pass, true, full.verdict);
  assert.equal(full.period, 4);
  assert.equal(full.dutyPct, 25);
  assert.equal(PioLevels.judge(bits(ref.series).slice(-128), L3.profile).pass, true);
  // the cost lesson, as a golden: the naive jmp port of L2's rows runs
  // one clk slower — jmp costs the cycle wrap does not
  const naive = PioLevels.judge(bits(caseOf(G3, 'jmp-cost').series), L3.profile);
  assert.equal(naive.pass, false);
  assert.match(naive.verdict, /period 5 .*outside/);
  // the wrong target: jmp 0 re-runs the preamble — structure, not syntax
  const j0 = PioLevels.judge(bits(caseOf(G3, 'jmp-target-0').series), L3.profile);
  assert.equal(j0.pass, false);
  assert.match(j0.verdict, /period 12 .*outside/);
});

test('l3 words are pio_model-equal and canonically spelled', () => {
  const prog = PioAsm.createProgram('c36-l3');
  prog.sidesetBits = 0;
  for (const row of [...L3.program.listing, ...L3.reference.listing]) {
    const w = PioAsm.assembleInstruction(row, prog, {}, `l3 row ${row}`);
    assert.equal(PioAsm.disassemble(w, false, 0), row, `${row} is not the canonical spelling`);
  }
  const st = PioLevels.programState(L3, PioAsm, VibeDriver);
  assert.deepEqual(st.words, G3.boot.words, 'the page boots the golden boot words');
  const words = new Array(32).fill(0);
  L3.reference.listing.forEach((row, i) => {
    words[i] = PioAsm.assembleInstruction(row, prog, {}, `l3 ref row ${i}`);
  });
  assert.deepEqual(words, G3.words, 'the reference assembles to the golden words');
});

// ---- C36: L5 The long blink — the [31] ceiling and the ds budget -----------
// The stretch level of chapter 1: the same 1:3 wave, sixteen times
// slower — high 16 of every 64 clk. No single row can wait 48 clk
// (SPEC-4-3's 5-bit budget), so the low time must split across rows;
// the wave window grows to see enough periods of the slow wave.
require('../levels/l5.js');
const L5 = PioLevels.get('l5');
const G5 = GOLDEN.levels.l5;

test('l5 registers complete: the long blink, the 512-sample window', () => {
  assert.equal(L5.id, 'l5');
  assert.equal(L5.name, 'The long blink');
  assert.equal(L5.chapter, 1);
  assert.ok(L5.goal.length > 8);
  // from scratch: the listing boots EMPTY
  assert.deepEqual(L5.program.listing, []);
  assert.equal(L5.program.sms[0].execctrl.wrapTop, 2);
  assert.equal(L5.program.sms[0].execctrl.wrapBot, 0);
  // the wave window: 64 clk/cycle needs 512 samples to hold the judge's
  // stability window (the level page is its own geometry — the sandbox
  // keeps 128)
  assert.equal(L5.waveWin, 512);
  // the chapter-1 vocabulary stays unlocked (knowledge is monotone)
  assert.deepEqual(L5.opcodes, ['set', 'jmp']);
  assert.equal(L5.profile.tier, 'exact');
  assert.equal(L5.profile.tiers.exact.periodLo, 64);
  assert.equal(L5.profile.tiers.exact.periodHi, 64);
  assert.equal(PioLevels.gateOpen(L5, {}), true);
  // the shipped answer: the 1:3 split — [15] / [31]+[15]
  assert.deepEqual(L5.reference.listing, [
    'set pins, 1 [15]',
    'set pins, 0 [31]',
    'set pins, 0 [15]',
  ]);
  assert.deepEqual(L5.reference.par, { words: 3, period: 64 });
});

test('the l5 wave contract: reference greens in both windows, near-misses red legibly', () => {
  const ref = caseOf(G5, 'reference');
  const full = PioLevels.judge(bits(ref.series), L5.profile);
  assert.equal(full.pass, true, full.verdict);
  assert.equal(full.period, 64);
  assert.equal(full.dutyPct, 25);
  // the browser judges the wave window — at 64 clk/cycle that window is
  // the level's own 512 samples, and the verdict must not depend on it
  assert.equal(PioLevels.judge(bits(ref.series).slice(-512), L5.profile).pass, true);
  // the empty boot never rises
  const boot = PioLevels.judge(bits(G5.boot.series), L5.profile);
  assert.equal(boot.pass, false);
  assert.match(boot.verdict, /never rose/);
  // the near-miss: one delay short of the split (period 63)
  const off1 = PioLevels.judge(bits(caseOf(G5, 'off-by-one').series), L5.profile);
  assert.equal(off1.pass, false);
  assert.match(off1.verdict, /period 63 .*outside/);
  // the forgotten third row: period 48
  assert.equal(PioLevels.judge(bits(caseOf(G5, 'one-row-short').series), L5.profile).pass, false);
  // both halves maxed at [31]: under the pinned wrap the two-row program
  // runs through the `·` row (a jmp 0 — it costs a clk), so period 65:
  // the empty row is not free, and the verdict says so
  const mx = PioLevels.judge(bits(caseOf(G5, 'both-maxed').series), L5.profile);
  assert.equal(mx.pass, false);
  assert.match(mx.verdict, /period 65 .*outside/);
});

test('l5 words are pio_model-equal and canonically spelled', () => {
  const prog = PioAsm.createProgram('c36-l5');
  prog.sidesetBits = 0;
  for (const row of L5.reference.listing) {
    const w = PioAsm.assembleInstruction(row, prog, {}, `l5 row ${row}`);
    assert.equal(PioAsm.disassemble(w, false, 0), row, `${row} is not the canonical spelling`);
  }
  assert.ok(PioLevels.programState(L5, PioAsm, VibeDriver).words.every((w) => w === 0));
  const words = new Array(32).fill(0);
  L5.reference.listing.forEach((row, i) => {
    words[i] = PioAsm.assembleInstruction(row, prog, {}, `l5 ref row ${i}`);
  });
  assert.deepEqual(words, G5.words, 'the reference assembles to the golden words');
});

// ---- C37: L4 Out of order — the scrambler (Parsons) -----------------------
// Comprehension by reordering: the rows arrive shuffled and the task is
// to trade them until the wave matches — zero generation load, the whole
// vocabulary is the given rows. The boot IS the canonical misconception:
// the once-flash ([7]) trapped inside the loop, so the flash comes round
// every period (period 14, legibly outside). The way out reads the jmp's
// semantics off the face: `jmp 1` names address 1, so the row at address
// 0 runs once — the flash belongs there. The second lesson ships as the
// high-before-jmp golden: the jmp's own clk holds the level of the row
// before it, so which row precedes the back edge is a real choice
// (duty 38, outside); and the dead-rows golden: rows after the jmp
// never execute at all.
require('../levels/l4.js');
const L4 = PioLevels.get('l4');
const G4 = GOLDEN.levels.l4;

test('l4 registers complete: the scramble flag, the permutation boot, no gate', () => {
  assert.equal(L4.id, 'l4');
  assert.equal(L4.name, 'Out of order');
  assert.equal(L4.chapter, 1);
  assert.ok(L4.goal.length > 8);
  // the scrambler posture: the listing gesture is the row trade — the
  // row editor never opens, the delay cell neither (the given rows are
  // fixed; only their addresses move)
  assert.equal(L4.scramble, true);
  // the boot is a true permutation of the reference: same rows, wrong
  // order (the player's whole move is reordering)
  assert.deepEqual([...L4.program.listing].sort(), [...L4.reference.listing].sort());
  assert.notDeepEqual(L4.program.listing, L4.reference.listing);
  // the jmp's target is part of the given vocabulary: address 1, the
  // loop entry the player must place a row at
  assert.ok(L4.program.listing.some((r) => /^jmp 1$/.test(r)));
  assert.ok(L4.panels.includes('delayCol'), 'reading [n] is the comprehension — the column stays');
  assert.ok(!L4.panels.includes('sideCol'), 'no side column until chapter 4');
  assert.ok(!L4.panels.includes('wrapSteppers'), 'the wrap steppers stay locked');
  // knowledge stays monotone (the chapter-1 vocabulary) even though the
  // scrambler never opens the editor the leash would scope
  assert.deepEqual(L4.opcodes, ['set', 'jmp']);
  // the same 8-clk 1:3 blink as the chapter's other levels, judged exact
  assert.equal(L4.profile.v, 1);
  assert.equal(L4.profile.tier, 'exact');
  assert.equal(L4.profile.tiers.exact.periodLo, 8);
  assert.equal(L4.profile.tiers.exact.periodHi, 8);
  // Parsons, not predict: the gate never locks
  assert.equal(PioLevels.gateOpen(L4, {}), true);
  // the shipped answer: the flash once, then the blink — the back edge
  // closes on a LOW row (the jmp's clk holds it)
  assert.deepEqual(L4.reference.listing, [
    'set pins, 1 [7]',
    'set pins, 1 [1]',
    'set pins, 0 [1]',
    'set pins, 0 [2]',
    'jmp 1',
  ]);
  assert.deepEqual(L4.reference.par, { words: 5, period: 8 });
});

test('the l4 wave contract: reference order green, the boot and planted wrong orders red', () => {
  // the boot: the flash trapped in the loop — it comes round every
  // period, legibly outside the 8-clk window
  const boot = PioLevels.judge(bits(G4.boot.series), L4.profile);
  assert.equal(boot.pass, false);
  assert.match(boot.verdict, /period 14 .*outside/);
  // the reference: flash once, then the 8-clk 1:3 blink — full series
  // and the wave window alike
  const ref = caseOf(G4, 'reference');
  const full = PioLevels.judge(bits(ref.series), L4.profile);
  assert.equal(full.pass, true, full.verdict);
  assert.equal(full.period, 8);
  assert.equal(full.dutyPct, 25);
  assert.equal(PioLevels.judge(bits(ref.series).slice(-128), L4.profile).pass, true);
  // the high row last: the jmp holds it — duty 38, the row before the
  // back edge is a real choice
  const hb = PioLevels.judge(bits(caseOf(G4, 'high-before-jmp').series), L4.profile);
  assert.equal(hb.pass, false);
  assert.match(hb.verdict, /duty 38% — outside/);
  // the jmp mid-listing: the rows after it never run — one flash, then
  // the wave goes flat (dead code is invisible to the monitor)
  const dead = PioLevels.judge(bits(caseOf(G4, 'dead-rows').series), L4.profile);
  assert.equal(dead.pass, false);
  assert.match(dead.verdict, /keep watching/);
});

test('l4 words are pio_model-equal, canonically spelled, and swap-equal', () => {
  const prog = PioAsm.createProgram('c37-l4');
  prog.sidesetBits = 0;
  for (const row of [...L4.program.listing, ...L4.reference.listing]) {
    const w = PioAsm.assembleInstruction(row, prog, {}, `l4 row ${row}`);
    assert.equal(PioAsm.disassemble(w, false, 0), row, `${row} is not the canonical spelling`);
  }
  // the page boots the golden's shuffled boot words
  const st = PioLevels.programState(L4, PioAsm, VibeDriver);
  assert.deepEqual(st.words, G4.boot.words);
  // a trade never adds or loses a word: boot and reference are the same
  // multiset of words, in different slots
  assert.deepEqual(
    [...st.words].sort((a, b) => a - b),
    [...G4.words].sort((a, b) => a - b),
  );
  const words = new Array(32).fill(0);
  L4.reference.listing.forEach((row, i) => {
    words[i] = PioAsm.assembleInstruction(row, prog, {}, `l4 ref row ${i}`);
  });
  assert.deepEqual(words, G4.words, 'the reference assembles to the golden words');
});

test('par dominates the l3/l4/l5 reference solutions on both axes', () => {
  for (const [L, G] of [
    [L3, G3],
    [L4, G4],
    [L5, G5],
  ]) {
    const used = G.words.filter((w) => w !== 0).length;
    assert.ok(used <= L.reference.par.words, `${L.id}: ${used} words > par`);
    const v = PioLevels.judge(bits(G.cases[0].series), L.profile);
    assert.ok(v.period <= L.reference.par.period, `${L.id}: ${v.period} clk/cycle > par`);
  }
});

// ---- C39: L6 Listen — the reading slice (stimulus + the RX judge) ------
// Chapter 2 opens: the world arrives on a wire. The level drives gpio1
// (the stimulus, one pattern cfg mapping 1:1 onto the engine's pattern
// contract), and the given program is the whole lesson — `in pins, 1`
// gathers the pin's bit into the ISR (bit 31 under the reset
// shift-right), `push` hands the word to the RX FIFO; the wrap reads
// again every 2 clk. The RX FIFO is 4 deep and the fifth push stalls
// (the honest machine), so acceptance is the FIRST FOUR pushed words
// against the driven pattern's first four sampled bits — the rx judge,
// exact by design (a value has no tolerance; the ladder lives on
// timing judges).
require('../levels/l6.js');
const L6 = PioLevels.get('l6');
const G6 = GOLDEN.levels.l6;
const { createFake } = require('./fake-engine.js');

test('l6 registers complete: the stimulus, the rx profile, the word face', () => {
  assert.equal(L6.id, 'l6');
  assert.equal(L6.name, 'Listen');
  assert.equal(L6.chapter, 2);
  assert.ok(L6.goal.length > 8);
  // the given: one pattern cfg per driven pin, spelled exactly like the
  // pattern contract the worker's cmd:'pattern' carries
  assert.deepEqual(L6.stimulus, [{ mode: 'square', pin: 1, period: 4 }]);
  // the reading debut: the ISR panel + the RX half of the fifo row. TX
  // is the feeder's (L9, chapter 3) — absence covers the tx half, the
  // pull connector, the osr, the feed and pattern panels both
  for (const key of ['transport', 'listing', 'wave', 'isr', 'rxfifo'])
    assert.ok(L6.panels.includes(key), `${key} is L6's surface`);
  for (const absent of ['txfifo', 'osr', 'pullconn', 'feed', 'pattern', 'frameMap', 'delayCol'])
    assert.ok(!L6.panels.includes(absent), `${absent} must stay absent in L6`);
  // no editor: predict → run only
  assert.deepEqual(L6.opcodes, []);
  // the rx judge: versioned, exact words, no ladder
  assert.equal(L6.profile.kind, 'rx');
  assert.equal(L6.profile.v, 1);
  assert.equal(L6.profile.tiers, undefined);
  assert.deepEqual(L6.profile.words, [0x80000000, 0, 0x80000000, 0]);
  // the word face: 32-bit candidates (the ISR's bits grammar), one of
  // them the answer
  assert.equal(L6.predict.face, 'isr');
  assert.ok(L6.predict.candidates.every((c) => c.bits.length === 32));
  assert.ok(L6.predict.candidates.some((c) => c.id === L6.predict.answer));
  // predict → run: the gate locks the first run of the given program
  assert.equal(PioLevels.gateOpen(L6, {}), false);
  assert.equal(PioLevels.gateOpen(L6, { predicted: true }), true);
  // the given program is the only honest one: par IS it
  assert.deepEqual(L6.reference.par, { words: 2, period: 2 });
});

test('the stimulus and word-face validation reject malformed levels', () => {
  const bad = (mutate, what) => {
    const d = structuredClone(L6);
    mutate(d);
    assert.throws(() => PioLevels.register(`l6-${what}`, d), Error, what);
  };
  // the stimulus: a list, one pattern per pin, the pattern contract's
  // own shape (even square periods, 0/1 bit strings)
  bad((d) => {
    d.stimulus = 'square';
  }, 'not-a-list');
  bad((d) => {
    d.stimulus = [];
  }, 'empty');
  bad((d) => {
    d.stimulus = [{ mode: 'nope', pin: 1 }];
  }, 'bad-mode');
  bad((d) => {
    d.stimulus = [{ mode: 'square', pin: 1, period: 5 }];
  }, 'odd-period');
  bad((d) => {
    d.stimulus = [
      { mode: 'square', pin: 1, period: 4 },
      { mode: 'square', pin: 1, period: 8 },
    ];
  }, 'same-pin-twice');
  bad((d) => {
    d.stimulus = [{ mode: 'bits', pin: 1, bits: '01x' }];
  }, 'bad-bits');
  // the rx profile: versioned words, 32-bit
  bad((d) => {
    d.profile = { ...d.profile, words: [0x100000000] };
  }, 'word-too-wide');
  bad((d) => {
    d.profile = { ...d.profile, words: [] };
  }, 'no-words');
  // the word face: a face is wave|isr, and isr candidates are words
  bad((d) => {
    d.predict = { ...d.predict, face: 'byte' };
  }, 'bad-face');
  bad((d) => {
    d.predict.candidates[0] = { ...d.predict.candidates[0], bits: '1010' };
  }, 'short-bits');
  // a square profile still demands its tiers
  assert.throws(
    () => PioLevels.register('l6-notiers', { ...L6, profile: { kind: 'square', v: 1, pin: 0 } }),
    /tier/,
  );
});

test('l6 words are pio_model-equal and canonically spelled; the boot is the reference', () => {
  const prog = PioAsm.createProgram('c39-l6');
  prog.sidesetBits = 0;
  for (const row of L6.program.listing) {
    const w = PioAsm.assembleInstruction(row, prog, {}, `l6 row ${row}`);
    assert.equal(PioAsm.disassemble(w, false, 0), row, `${row} is not the canonical spelling`);
  }
  const st = PioLevels.programState(L6, PioAsm, VibeDriver);
  assert.deepEqual(st.words, G6.words);
  assert.equal(st.sms[0].pinctrl.inBase, 1, 'the IN mapping names the driven pin');
  // predict→run: the listing IS the reference — no separate boot case
  assert.equal(G6.boot, undefined);
  assert.deepEqual(L6.program.listing, ['in pins, 1', 'push block']);
});

test('the l6 word contract: reference greens, the planted wrongs red legibly', () => {
  const ref = caseOf(G6, 'reference');
  // the pushed words decode to the driven pattern's bits — the
  // committed golden's rx, replayed through the judge
  assert.deepEqual(ref.rx, [0x80000000, 0, 0x80000000, 0]);
  const v = PioLevels.judge(ref.rx, L6.profile);
  assert.equal(v.pass, true, v.verdict);
  assert.equal(v.code, 'pass');
  assert.match(v.verdict, /4 words/);
  // never-push: the gatherer without the hand-off — nothing to judge
  const np = PioLevels.judge(caseOf(G6, 'never-push').rx, L6.profile);
  assert.deepEqual(caseOf(G6, 'never-push').rx, []);
  assert.equal(np.pass, false);
  assert.equal(np.code, 'nowords');
  assert.match(np.verdict, /no words/);
  // in-count-wrong: two bits per word shift the bit one position low —
  // the verdict names the first divergent bit (the near-miss face)
  const icw = PioLevels.judge(caseOf(G6, 'in-count-wrong').rx, L6.profile);
  assert.deepEqual(caseOf(G6, 'in-count-wrong').rx, [0x40000000, 0, 0x40000000, 0]);
  assert.equal(icw.pass, false);
  assert.equal(icw.code, 'diverge');
  assert.equal(icw.verdict, 'word 1 bit 31 — got 0, want 1');
  // a partial run keeps watching (3 of 4 words in)
  assert.equal(PioLevels.judge(ref.rx.slice(0, 3), L6.profile).code, 'watching');
  // the standing defect hook: any pushed words pass — the lens
  // masquerading as a judge, divergence demonstrated in-process
  assert.equal(
    PioLevels.judge(caseOf(G6, 'never-push').rx, L6.profile, { judge: true }).pass,
    false,
    'no words at all stay red even defective',
  );
  assert.equal(
    PioLevels.judge(caseOf(G6, 'in-count-wrong').rx, L6.profile, { judge: true }).pass,
    true,
  );
  assert.equal(PioLevels.judge(ref.rx, L6.profile).pass, true, 'clean stays green');
});

test('the stimulus composes lockstep with the golden series (driver ↔ mirror)', () => {
  // the golden's stim series is _SandboxMirror's composition over the
  // level's exact load timeline; the driver — the same client core the
  // worker runs — must compose the same gpio_in per rendered clk from
  // the level's own stimulus cfg, armed before the load (the shell's
  // order). This is the engine-side pin of setStimulus + the input
  // history, the pattern machinery's own gate.
  const drv = VibeDriver.create(createFake());
  drv.setStimulus(L6.stimulus);
  drv.load(PioLevels.programState(L6, PioAsm, VibeDriver));
  drv.run(160);
  const got = drv
    .allGpioIn()
    .map((w) => (w >>> 1) & 1)
    .join('');
  const golden = caseOf(G6, 'reference').stim['1'];
  assert.ok(golden.length > got.length, 'the golden replay is at least as long');
  assert.equal(
    golden.slice(0, got.length),
    got,
    'the driver composed a different stimulus than the mirror',
  );
  // the wave window's stimulus row carries the same series (windowed)
  const st = drv.getState();
  assert.equal(st.wave.stim.length, 1);
  assert.equal(st.wave.stim[0].pin, 1);
  assert.equal(st.wave.stim[0].bits.join(''), got.slice(-128));
});

test('the pushed-word mirror latches the pre-edge ISR at the push strobe', () => {
  // rxSeen is the judge's browser-side input: the driver latches the
  // ISR sample of the completing push clk (SPEC-16-1's start-of-clk
  // view — exactly the word the push retires), in push order
  const fake = createFake();
  const S = fake.S;
  const drv = VibeDriver.create(fake);
  drv.load(VibeDriver.EMPTY);
  assert.deepEqual(drv.getState().sms[0].rxSeen, []);
  fake.script([
    { strobes0: S.S_RX_PUSH, isr0: 0x80000000 },
    { strobes0: S.S_RX_PUSH, isr0: 0 },
    { strobes0: S.S_RX_PUSH, isr0: 0xa5a5a5a5 },
  ]);
  drv.run(3);
  assert.deepEqual(drv.getState().sms[0].rxSeen, [0x80000000, 0, 0xa5a5a5a5]);
  // the judge's browser path is this mirror: the same rxJudge that
  // greens the golden reds a divergent latch (the near-miss face)
  assert.equal(PioLevels.judge([0x80000000, 0], L6.profile).pass, false);
  assert.equal(PioLevels.judge(drv.getState().sms[0].rxSeen, L6.profile).code, 'diverge');
});

test('par dominates the l6 given program (front-trivial, still pinned)', () => {
  const used = G6.words.filter((w) => w !== 0).length;
  assert.ok(used <= L6.reference.par.words, `${used} words > par`);
  assert.equal(used, L6.reference.par.words, 'the given program IS the par — front-trivial');
});

// ---- C40: L7 Echo — jmp pin gets its job, the decode judge debuts ----
// Chapter 2's make level: the world drives a byte's UART frame on gpio2
// (8 clk/bit — start 0, D0..D7 LSB-first, stop 1) while the enable square
// on gpio1 marks the speaking window, and the task is the gated echo:
// copy the frame to gpio0 one bit-time at a time. The copy in the
// set+in+out+jmp vocabulary is the branchy pair — `jmp pin` (JMP_PIN =
// the data pin) testing the bit, `set pins` driving its value, the
// delays holding each bit for its whole bit-time (the gate the player
// writes is the RATE: the ungated racer skews). `out` cannot copy — the
// OSR is empty without a pull (the in/out-belief golden: the line never
// rises) — and the decode judge (SPEC-16-9 run semantics, the
// [BIT_LO,BIT_HI] idiom as the tier ladder) reads the OUTPUT wave.
require('../levels/l7.js');
const L7 = PioLevels.get('l7');
const G7 = GOLDEN.levels.l7;
// the driven byte 0x33, LSB-first at 8 clk/bit, inside the enable-high
// window (clks 80..159 of the stimulus), idle-high before and after
const L7_FRAME = '0'.repeat(8) + '1'.repeat(16) + '0'.repeat(16) + '1'.repeat(16) + '0'.repeat(16);
const L7_DATA = '1'.repeat(80) + L7_FRAME + '1'.repeat(8) + '1'.repeat(96);

test('l7 registers complete: the gated echo, the uart profile, the pin condition', () => {
  assert.equal(L7.id, 'l7');
  assert.equal(L7.name, 'Echo');
  assert.equal(L7.chapter, 2);
  assert.ok(L7.goal.length > 8);
  // the stimulus: the enable square narrates the speaking window, the
  // data bits carry the frame (aligned: the frame plays while enable is
  // high, the line idles while it is low — the echo's hold)
  assert.deepEqual(L7.stimulus, [
    { mode: 'square', pin: 1, period: 160 },
    { mode: 'bits', pin: 2, bits: L7_DATA },
  ]);
  // the wiring: JMP_PIN names the data pin (the copy's test), IN_BASE
  // reads it, SET/OUT drive gpio0
  assert.equal(L7.program.sms[0].execctrl.jmpPin, 2);
  assert.equal(L7.program.sms[0].pinctrl.inBase, 2);
  assert.equal(L7.program.sms[0].pinctrl.setCnt, 1);
  assert.equal(L7.program.sms[0].pinctrl.outCnt, 1);
  // the make-level surface: the reading leg stays (isr/rxfifo), the
  // delay column carries the bit-time gate, and the frame map debuts as
  // the wave's subgoal labels (START/D0..D7/STOP under the uart lens)
  for (const key of ['transport', 'listing', 'wave', 'delayCol', 'frameMap', 'isr', 'rxfifo'])
    assert.ok(L7.panels.includes(key), `${key} is L7's surface`);
  for (const absent of [
    'txfifo',
    'osr',
    'pullconn',
    'feed',
    'pattern',
    'wrapSteppers',
    'monitorAux',
  ])
    assert.ok(!L7.panels.includes(absent), `${absent} must stay absent in L7`);
  // the leash grows the reading vocabulary; the pin condition debuts
  assert.deepEqual(L7.opcodes, ['set', 'in', 'out', 'jmp']);
  assert.deepEqual(L7.conds, ['pin']);
  // the decode judge: versioned, expected bytes = the driven data, the
  // [BIT_LO,BIT_HI] skew window as the tier ladder (SPEC-16-9)
  assert.equal(L7.profile.kind, 'uart');
  assert.equal(L7.profile.v, 1);
  assert.equal(L7.profile.pin, 0);
  assert.equal(L7.profile.tier, 'exact');
  assert.deepEqual(L7.profile.bytes, [0x33]);
  assert.deepEqual(L7.profile.tiers.exact, { bitLo: 8, bitHi: 8 });
  // the frame is finite, so the wave keeps the readable default (128 —
  // unlike L5's periodic wave, no stability window needs whole periods
  // at every phase; the judge passes at the live moment, the sliding
  // window below)
  assert.equal(L7.waveWin, undefined);
  // a make level boots empty and never locks the gate
  assert.deepEqual(L7.program.listing, []);
  assert.equal(PioLevels.gateOpen(L7, {}), true);
  // the reference rides the `·` row home: the high path's set returns
  // through the empty row 3 (a free jmp 0 that still costs its clk —
  // the L5 lesson recurring, budgeted into the [5]) — 3 words, not 4
  assert.deepEqual(L7.reference.listing, ['jmp pin, 2', 'set pins, 0 [6]', 'set pins, 1 [5]']);
  assert.deepEqual(L7.reference.par, { words: 3, period: 8 });
});

test('the l7 uart-profile and conds validation reject malformed levels', () => {
  const bad = (mutate, what) => {
    const d = structuredClone(L7);
    mutate(d);
    assert.throws(() => PioLevels.register(`l7-${what}`, d), Error, what);
  };
  // the bytes: 8-bit values, at least one
  bad((d) => {
    d.profile = { ...d.profile, bytes: [0x100] };
  }, 'byte-too-wide');
  bad((d) => {
    d.profile = { ...d.profile, bytes: [] };
  }, 'no-bytes');
  // the tiers: the [BIT_LO,BIT_HI] window per bit-time
  bad((d) => {
    d.profile.tiers.exact = { bitLo: 9, bitHi: 8 };
  }, 'window-inverted');
  bad((d) => {
    delete d.profile.tiers.exact;
  }, 'no-active-tier');
  bad((d) => {
    d.profile.tiers.exact = { bitLo: 0, bitHi: 8 };
  }, 'zero-window');
  // the conds whitelist: known spellings only (the assembler's table)
  bad((d) => {
    d.conds = 'pin';
  }, 'conds-not-a-list');
  bad((d) => {
    d.conds = ['pin', 'maybe'];
  }, 'cond-unknown');
});

test('l7 words are pio_model-equal and canonically spelled; the boot is empty', () => {
  const prog = PioAsm.createProgram('c40-l7');
  prog.sidesetBits = 0;
  for (const row of [...L7.program.listing, ...L7.reference.listing]) {
    const w = PioAsm.assembleInstruction(row, prog, {}, `l7 row ${row}`);
    assert.equal(PioAsm.disassemble(w, false, 0), row, `${row} is not the canonical spelling`);
  }
  assert.ok(PioLevels.programState(L7, PioAsm, VibeDriver).words.every((w) => w === 0));
  const words = new Array(32).fill(0);
  L7.reference.listing.forEach((row, i) => {
    words[i] = PioAsm.assembleInstruction(row, prog, {}, `l7 ref row ${i}`);
  });
  assert.deepEqual(words, G7.words, 'the reference assembles to the golden words');
  // the lens pins to the output under the uart receiver (the name
  // programState already anticipated)
  const st = PioLevels.programState(L7, PioAsm, VibeDriver);
  assert.deepEqual(st.lens, { mode: 'uart', pin: 0 });
});

test('the l7 wave contract: the reference decodes 33, the wrongs red legibly', () => {
  // the reference: the gated echo — one bit-time per bit, the stop
  // merged into the idle tail (SPEC-16-9: costs nothing)
  const ref = caseOf(G7, 'reference');
  const full = PioLevels.judge(bits(ref.series), L7.profile);
  assert.equal(full.pass, true, full.verdict);
  assert.equal(full.code, 'pass');
  assert.match(full.verdict, /33/);
  // the browser judges the wave window as it slides (the driver's last
  // 128 samples) — a finite frame leaves every fixed window eventually,
  // so the live contract: the reference passes at the moment its stop
  // completes (SOME window position), and a perturbed echo never passes
  // at ANY position
  const winJudge = (series, profile, win = 128) => {
    for (let k = win; k <= series.length; k++)
      if (PioLevels.judge(bits(series.slice(k - win, k)), profile).pass) return true;
    return false;
  };
  assert.equal(winJudge(ref.series, L7.profile), true, 'the live window passes the echo');
  // the empty boot: the parked machine never drives — the line never fell
  const boot = PioLevels.judge(bits(G7.boot.series), L7.profile);
  assert.equal(boot.pass, false);
  assert.equal(boot.code, 'idle');
  // the ungated copy (the racer): no bit-time gate, the runs skew —
  // the near-miss names the first bad run
  const race = PioLevels.judge(bits(caseOf(G7, 'ungated-echo').series), L7.profile);
  assert.equal(race.pass, false, 'the ungated copy must not pass the exact tier');
  assert.equal(race.code, 'timing');
  assert.match(race.verdict, /outside \(8\.\.8 clk\/bit\)/);
  assert.equal(
    winJudge(caseOf(G7, 'ungated-echo').series, L7.profile),
    false,
    'the racer never passes at any window position',
  );
  // the ladder is real: the relaxed window admits the racer's skew
  const relaxed = { ...L7.profile, tier: 'relaxed' };
  assert.equal(PioLevels.judge(bits(caseOf(G7, 'ungated-echo').series), relaxed).pass, true);
  // the dropped bit: the 9/8 loop drifts through the frame — the exact
  // tier reds the run, the relaxed tier decodes a different byte and
  // names the bit (the value face: one bit wrong reads as one bit)
  const drop = PioLevels.judge(bits(caseOf(G7, 'dropped-bit').series), L7.profile);
  assert.equal(drop.pass, false);
  assert.match(drop.verdict, /D1 runs 18 clk/);
  assert.equal(winJudge(caseOf(G7, 'dropped-bit').series, L7.profile), false);
  const dropR = PioLevels.judge(bits(caseOf(G7, 'dropped-bit').series), relaxed);
  assert.equal(dropR.pass, false);
  assert.equal(dropR.code, 'data');
  assert.equal(dropR.verdict, 'byte 1 bit D0 — got 0, want 1');
  // the in/out belief (the L6 instinct): out reads an empty OSR — the
  // line never rises, the echo never starts
  const io = PioLevels.judge(bits(caseOf(G7, 'in-out-belief').series), L7.profile);
  assert.equal(io.pass, false);
  assert.equal(io.code, 'idle');
  assert.equal(winJudge(caseOf(G7, 'in-out-belief').series, L7.profile), false);
});

test('the uart judge codes: the band face never parses the prose', () => {
  const ones = bits('1'.repeat(64));
  assert.equal(PioLevels.judge([], L7.profile).code, 'awaiting');
  assert.equal(PioLevels.judge(ones, L7.profile).code, 'idle');
  // a half-arrived frame keeps watching (the stop never came — the
  // window ends on a legal run, mid-frame)
  const half = bits('1'.repeat(8) + '0'.repeat(8) + '1'.repeat(16) + '0'.repeat(16));
  assert.equal(PioLevels.judge(half, L7.profile).code, 'watching');
  // an inverted echo decodes a different byte: the data code, the bit named
  const inv = bits(
    '1'.repeat(8) +
      '0'.repeat(8) +
      '1'.repeat(8) +
      '0'.repeat(8) +
      '1'.repeat(8) +
      '0'.repeat(8) +
      '1'.repeat(8) +
      '0'.repeat(8) +
      '1'.repeat(8) +
      '0'.repeat(8) +
      '1'.repeat(16),
  );
  assert.equal(PioLevels.judge(inv, L7.profile).code, 'data');
  // the standing defect hook: the byte comparison skipped — any decoded
  // frame passes; the divergence demonstrated in-process
  assert.equal(PioLevels.judge(inv, L7.profile, { judge: true }).pass, true);
  assert.equal(PioLevels.judge(inv, L7.profile).pass, false, 'clean stays red');
  assert.equal(
    PioLevels.judge(ones, L7.profile, { judge: true }).pass,
    false,
    'no frame at all stays red even defective',
  );
});

test('the l7 leash: jmp offers the pin condition — and only it', () => {
  // L7: the pin condition debuts (always = digits at the first slot, as ever)
  const wl = { opcodes: L7.opcodes, conds: L7.conds };
  assert.deepEqual(
    RowComplete.analyze('jmp ', wl).cands.map((c) => c.t),
    ['pin'],
    "the condition menu offers exactly the level's unlocked conditions",
  );
  assert.deepEqual(
    RowComplete.analyze('jmp x', wl).cands,
    [],
    'a locked condition is never suggested',
  );
  // the chapter-1 levels never offered conditions at all — the leash
  // closes the teaching-ahead gap (their jmps are unconditional)
  for (const L of [L3, L4, L5]) {
    const c = RowComplete.analyze('jmp ', { opcodes: L.opcodes, conds: [] }).cands;
    assert.deepEqual(c, [], `${L.id}: the condition menu stays shut before L7`);
  }
  // the sandbox menu stays whole — no whitelist, all seven conditions
  assert.deepEqual(
    RowComplete.analyze('jmp ').cands.map((c) => c.t),
    ['!x', 'x--', '!y', 'y--', 'x != y', 'pin', '!osre'],
  );
});

test('targetGlyph draws the uart frame: the byte glyph is the tier as geometry', () => {
  const g = PioLevels.targetGlyph(L7.profile);
  // the representative frame at the drawn bit-time: start, the byte's
  // runs (2-bit symbols merge — SPEC-16-9 run semantics), the stop
  assert.equal(g.clks, 80);
  assert.equal(g.bits, L7_FRAME + '1'.repeat(8));
  // the two acceptance windows after the frame's first fall: where the
  // next edge may land (one bit-time: [BIT_LO, BIT_HI]) and the edge
  // after that (two bit-times) — the square grammar, uart numbers
  assert.deepEqual([g.fallFrom, g.fallTo], [8, 8]);
  assert.deepEqual([g.nextFrom, g.nextTo], [16, 16]);
  // the relaxed window draws a wider template, still the tier's numbers
  const r = PioLevels.targetGlyph({ ...L7.profile, tier: 'relaxed' });
  assert.deepEqual([r.fallFrom, r.fallTo], [6, 10]);
  assert.deepEqual([r.nextFrom, r.nextTo], [12, 20]);
  // purity
  assert.deepEqual(PioLevels.targetGlyph(L7.profile), g);
});

// targetGlyph is the pure descriptor the band glyphs and the wave-panel
// gates render: the profile tier itself as geometry — a representative
// accepted cycle plus the two windows the judge actually checks (the
// falling edge inside the duty band, the next rise inside the period
// band). The judge stays the judge; this only makes its tolerances
// visible, so the descriptor's numbers ARE the tier's numbers.
test('targetGlyph: the tier as geometry, for every shipped level', () => {
  for (const L of [L0, L1, L2, L3, L4, L5]) {
    const tp = L.profile.tiers[L.profile.tier];
    const g = PioLevels.targetGlyph(L.profile);
    // the representative cycle is the widest accepted one, one rise first
    assert.equal(g.clks, tp.periodHi, `${L.id}: clks`);
    assert.equal(g.bits.length, tp.periodHi, `${L.id}: bits length`);
    assert.equal(g.bits[0], '1', `${L.id}: a cycle starts at the rise`);
    assert.ok(g.bits.endsWith('0'), `${L.id}: a cycle ends low before the next rise`);
    // the drawn falling edge sits inside the duty window — the template
    // never draws a wave the tier itself would red
    const hi = g.bits.indexOf('0');
    assert.ok(
      g.fallFrom <= hi && hi <= g.fallTo,
      `${L.id}: high ${hi} clk outside the duty window [${g.fallFrom}, ${g.fallTo}]`,
    );
    // the windows are the tier's own tolerances, in clk — honest by design
    const eps = 1e-9;
    assert.ok(Math.abs(g.fallFrom - (tp.periodHi * tp.dutyLoPct) / 100) < eps, `${L.id}: fallFrom`);
    assert.ok(Math.abs(g.fallTo - (tp.periodHi * tp.dutyHiPct) / 100) < eps, `${L.id}: fallTo`);
    assert.deepEqual(
      [g.nextFrom, g.nextTo],
      [tp.periodLo, tp.periodHi],
      `${L.id}: next-rise window`,
    );
    // purity: the same profile draws the same glyph twice
    assert.deepEqual(PioLevels.targetGlyph(L.profile), g, `${L.id}: not pure`);
  }
});

test('targetGlyph: l3 spot values and the kind contract', () => {
  // L3 exact: 4..4 clk, 15..40% — the glyph is a 4-clk cycle, one high,
  // the fall free to land anywhere in [0.6, 1.6] clk, the next rise at
  // exactly clk 4 (a zero-width window reads as a gold tick)
  assert.deepEqual(PioLevels.targetGlyph(L3.profile), {
    clks: 4,
    bits: '1000',
    fallFrom: 0.6,
    fallTo: 1.6,
    nextFrom: 4,
    nextTo: 4,
  });
  // the glyph shares the judge's receiver contract — square and uart
  // draw (the rx judge has no windows: a value has no tolerance)
  assert.throws(() => PioLevels.targetGlyph(L6.profile), /no receiver/);
});

test('the judge carries a machine-readable code for the band face', () => {
  // the visual monitor maps verdicts to a status word by code, never by
  // parsing the prose (the strings stay pinned by the wave-contract
  // tests above; the code is additive glue surface)
  assert.equal(PioLevels.judge([], L3.profile).code, 'awaiting');
  assert.equal(PioLevels.judge([0, 0, 0], L3.profile).code, 'noblink');
  assert.equal(PioLevels.judge(bits('0110110'), L3.profile).code, 'watching');
  // period 13 with duty in range: the period code, not duty
  const boot = PioLevels.judge(bits(G3.boot.series), L3.profile);
  assert.equal(boot.code, 'period');
  // duty red: a period-4 wave held 3 of 4 high (duty 75 > 40) — the
  // period is in-window so the duty clause is the first to fail
  const duty = PioLevels.judge(bits('0111'.repeat(8)), L3.profile);
  assert.equal(duty.code, 'duty');
  const pass = PioLevels.judge(bits(G3.cases[0].series), L3.profile);
  assert.equal(pass.code, 'pass');
});

// ---- C41: L8 Fencepost — the designed off-by-one, x-- gets its slot ----
// Chapter 2's closing make level: the world ticks its bits on gpio1 (a
// 2-clk low tick then sixteen 1s, period 18 clk), and the task is the
// counting gather: `set x` arms the stepper, `jmp x--` closes the loop
// (SPEC-3.1-4: the test sees the PRE-decrement value, X always
// decrements), `push` hands the word to the RX FIFO. The fencepost is
// the designed near-miss, legible ON THE DECODED VALUE: the correct
// word is 11111110 (0xFE — the tick's 0 plus seven 1s); one bit too
// many pushes 11111111 (the extra 1 shifted the 0 off the end — the
// verdict lands at bit 24), one too few pushes 1111110 (a 1 missing —
// bit 25). The long run of 1s is the tuning: the one-clk shift the
// extra bit causes stays invisible until the word's edge.
// The X/Y scratch panel debuts (the stepper role — Sajaniemi's
// roles-in-use); acceptance is C39's RX judge over the first four
// pushed words (the 18-clk gather lap over the 18-clk pattern reads
// the same word every lap, and the fifth push stalls on the full FIFO
// — the honest machine, L6's story recurring).
require('../levels/l8.js');
const L8 = PioLevels.get('l8');
const G8 = GOLDEN.levels.l8;
// the driven pattern: a 2-clk low tick then sixteen 1s (nine 2-clk
// slots, 0,1,1,1,1,1,1,1,1), period 18 clk — the window's long run of
// 1s is what makes the fencepost legible on the decoded value
const L8_PERIOD = '001111111111111111';

test('l8 registers complete: the stepper leash, the x-- slot, the xy debut', () => {
  assert.equal(L8.id, 'l8');
  assert.equal(L8.name, 'Fencepost');
  assert.equal(L8.chapter, 2);
  assert.ok(L8.goal.length > 8);
  // the given: one pattern cfg — the driven bits, 18-clk periodic
  assert.equal(L8.stimulus.length, 1);
  assert.equal(L8.stimulus[0].mode, 'bits');
  assert.equal(L8.stimulus[0].pin, 1);
  assert.equal(L8.stimulus[0].bits.length, 256);
  assert.equal(L8.stimulus[0].bits.slice(0, 18), L8_PERIOD);
  assert.equal(L8.stimulus[0].bits.slice(18, 36), L8_PERIOD);
  // the wiring: IN_BASE reads the driven pin; the set lane is inert
  // (set writes X, never pins); the wrap loops the whole 4-row program
  assert.equal(L8.program.sms[0].pinctrl.inBase, 1);
  assert.equal(L8.program.sms[0].execctrl.wrapTop, 3);
  assert.equal(L8.program.sms[0].execctrl.wrapBot, 0);
  // the make-level surface: the reading leg stays, the X/Y scratch
  // debuts (the stepper role), and the delay column stays SHUT —
  // structure, not delay, is the lesson (the card)
  for (const key of ['transport', 'listing', 'wave', 'isr', 'rxfifo', 'xy'])
    assert.ok(L8.panels.includes(key), `${key} is L8's surface`);
  for (const absent of [
    'txfifo',
    'osr',
    'pullconn',
    'feed',
    'pattern',
    'frameMap',
    'wrapSteppers',
    'monitorAux',
    'delayCol',
    'regs',
  ])
    assert.ok(!L8.panels.includes(absent), `${absent} must stay absent in L8`);
  // the leash: the gather vocabulary; the x-- condition debuts (L7's
  // pin is not this task's — the leash is task-scoped, the L7 precedent)
  assert.deepEqual(L8.opcodes, ['set', 'in', 'push', 'jmp']);
  assert.deepEqual(L8.conds, ['x--']);
  // the rx judge again: versioned, exact words — the gather's byte,
  // four times (the FIFO fills, the fifth push stalls: honest)
  assert.equal(L8.profile.kind, 'rx');
  assert.equal(L8.profile.v, 1);
  assert.equal(L8.profile.pin, 1);
  assert.deepEqual(L8.profile.words, [0xfe000000, 0xfe000000, 0xfe000000, 0xfe000000]);
  // a make level boots empty and never locks the gate
  assert.deepEqual(L8.program.listing, []);
  assert.equal(PioLevels.gateOpen(L8, {}), true);
  // the shipped answer: the stepper armed at N-1 (SPEC-3.1-4 — set x, 7
  // gathers 8), the 2-clk loop, the hand-off
  assert.deepEqual(L8.reference.listing, ['set x, 7', 'in pins, 1', 'jmp x--, 1', 'push block']);
  assert.deepEqual(L8.reference.par, { words: 4, period: 2 });
});

test('l8 words are pio_model-equal and canonically spelled; the boot is empty', () => {
  const prog = PioAsm.createProgram('c41-l8');
  prog.sidesetBits = 0;
  for (const row of [...L8.program.listing, ...L8.reference.listing]) {
    const w = PioAsm.assembleInstruction(row, prog, {}, `l8 row ${row}`);
    assert.equal(PioAsm.disassemble(w, false, 0), row, `${row} is not the canonical spelling`);
  }
  assert.ok(PioLevels.programState(L8, PioAsm, VibeDriver).words.every((w) => w === 0));
  const words = new Array(32).fill(0);
  L8.reference.listing.forEach((row, i) => {
    words[i] = PioAsm.assembleInstruction(row, prog, {}, `l8 ref row ${i}`);
  });
  assert.deepEqual(words, G8.words, 'the reference assembles to the golden words');
  const st = PioLevels.programState(L8, PioAsm, VibeDriver);
  assert.deepEqual(st.lens, { mode: 'off', pin: 1 }, 'reading is invisible on the pins');
});

test('the l8 word contract: the gather greens, the fencepost reds both ways', () => {
  // the reference: four identical words — the 18-clk gather lap reads
  // the 18-clk pattern at the same phase every lap (pio_model's own
  // arithmetic, committed below)
  const ref = caseOf(G8, 'reference');
  assert.deepEqual(ref.rx, [0xfe000000, 0xfe000000, 0xfe000000, 0xfe000000]);
  const v = PioLevels.judge(ref.rx, L8.profile);
  assert.equal(v.pass, true, v.verdict);
  assert.equal(v.code, 'pass');
  assert.match(v.verdict, /4 words/);
  // the designed misconception, one bit too many: set x, 8 — the X=1
  // jump still fires (SPEC-3.1-4), the ninth 1 shifts the tick's 0 off
  // the end of the word and the verdict lands at the window's edge
  const many = caseOf(G8, 'fencepost-too-many');
  assert.deepEqual(many.rx[0], 0xff000000);
  const vm = PioLevels.judge(many.rx, L8.profile);
  assert.equal(vm.pass, false);
  assert.equal(vm.code, 'diverge');
  assert.equal(vm.verdict, 'word 1 bit 24 — got 1, want 0');
  // one bit too few: set x, 6 — the eighth 1 never arrives, a 1 is
  // missing one position inside the edge
  const few = caseOf(G8, 'fencepost-too-few');
  assert.deepEqual(few.rx[0], 0xfc000000);
  const vf = PioLevels.judge(few.rx, L8.profile);
  assert.equal(vf.pass, false);
  assert.equal(vf.verdict, 'word 1 bit 25 — got 0, want 1');
  // the count-is-width belief: in pins, 8 samples EIGHT ADJACENT PINS
  // once (gpio1..gpio8), not one pin eight times — the word is one bit
  // at 24, everything else zero
  const wide = caseOf(G8, 'count-is-width');
  assert.deepEqual(wide.rx[0], 0x01000000);
  const vw = PioLevels.judge(wide.rx, L8.profile);
  assert.equal(vw.pass, false);
  assert.equal(vw.verdict, 'word 1 bit 31 — got 0, want 1');
  // a partial gather keeps watching (3 of 4 words in)
  assert.equal(PioLevels.judge(ref.rx.slice(0, 3), L8.profile).code, 'watching');
  // the standing defect hook: any pushed words pass — divergence
  // demonstrated in-process, clean stays green
  assert.equal(PioLevels.judge(few.rx, L8.profile, { judge: true }).pass, true);
  assert.equal(PioLevels.judge(ref.rx, L8.profile).pass, true);
});

test('the l8 stimulus composes lockstep with the golden series (driver ↔ mirror)', () => {
  // the empty boot's own load timeline (no imem writes) — the golden's
  // boot case replays exactly it, so the driver's composed input per
  // rendered clk must match the mirror's, clk for clk
  const drv = VibeDriver.create(createFake());
  drv.setStimulus(L8.stimulus);
  drv.load(PioLevels.programState(L8, PioAsm, VibeDriver));
  drv.run(160);
  const got = drv
    .allGpioIn()
    .map((w) => (w >>> 1) & 1)
    .join('');
  const golden = G8.boot.stim['1'];
  assert.ok(golden.length > got.length, 'the golden replay is at least as long');
  assert.equal(
    golden.slice(0, got.length),
    got,
    'the driver composed a different stimulus than the mirror',
  );
  // the wave window's stimulus row carries the same series (windowed)
  const st = drv.getState();
  assert.equal(st.wave.stim.length, 1);
  assert.equal(st.wave.stim[0].pin, 1);
  assert.equal(st.wave.stim[0].bits.join(''), got.slice(-128));
});

test('par dominates the l8 reference on both axes (front-champion)', () => {
  const used = G8.words.filter((w) => w !== 0).length;
  assert.equal(used, L8.reference.par.words, 'the reference is the 4-word champion');
  // the period axis names its own clock: 2 clk/bit — the in+jmp loop's
  // steady rate, pinned by the hyperopt front (the drift gate)
  assert.equal(L8.reference.par.period, 2);
});

test('the l8 leash: jmp offers the x-- slot — and only it', () => {
  // L8: the decrement condition debuts (always = digits at the first
  // slot, as ever); the pin condition is not this task's — the leash is
  // task-scoped, the L7 precedent for opcodes
  const wl = { opcodes: L8.opcodes, conds: L8.conds };
  assert.deepEqual(
    RowComplete.analyze('jmp ', wl).cands.map((c) => c.t),
    ['x--'],
    "the condition menu offers exactly the level's unlocked conditions",
  );
  assert.deepEqual(
    RowComplete.analyze('jmp pin', wl).cands,
    [],
    'a locked condition is never suggested',
  );
  // the mnemonic menu offers the gather vocabulary (the C32 order)
  assert.deepEqual(
    RowComplete.analyze('', wl).cands.map((c) => c.t),
    ['jmp', 'in', 'push', 'set'],
  );
  // set's own slots stay live under the leash: the stepper arms with a
  // 5-bit immediate
  assert.ok(RowComplete.analyze('set ', wl).cands.some((c) => c.t === 'x'));
  // the sandbox menu stays whole
  assert.deepEqual(
    RowComplete.analyze('jmp ').cands.map((c) => c.t),
    ['!x', 'x--', '!y', 'y--', 'x != y', 'pin', '!osre'],
  );
});

// ============ C42: the campaign — the registry as the map's source ============
// The landing page (web/index.html) is DOM glue over levels.js module
// logic: the CHAPTERS table, sessionKey (the per-level key spelling
// both pages share), campaign (order/solved/frontier/chapters over the
// EXISTING per-level keys — no new storage shape on the landing card),
// and parText (the named-clock par label the band reveals on solve and
// the map shows on solved rows). These legs ran red first against the
// pre-C42 module: PioLevels.campaign was not a function.

test('the chapter table ships with its levels, not ahead of them', () => {
  // every registered level's chapter carries a title...
  for (const id of PioLevels.all())
    assert.ok(
      PioLevels.CHAPTERS.some((c) => c.n === PioLevels.get(id).chapter),
      `${id}'s chapter has no CHAPTERS title`,
    );
  // ...and no title arrives before its first level (LEVELS-NOTES prose
  // does not ship ahead of its own grilling — the registry is the source)
  const shipped = new Set(PioLevels.all().map((id) => PioLevels.get(id).chapter));
  for (const c of PioLevels.CHAPTERS)
    assert.ok(shipped.has(c.n), `chapter ${c.n} (${c.title}) has no shipped level`);
  // the titles are the LEVELS-NOTES chapter sketch, in order
  assert.deepEqual(
    PioLevels.CHAPTERS.map((c) => c.title),
    ['First light', 'Time and loops', 'Reading the world'],
  );
});

test('a level cannot register a chapter the table does not name', () => {
  const ahead = { ...PioLevels.get('l0'), id: 'lx', chapter: 7 };
  assert.throws(() => PioLevels.register('lx', ahead), /chapter 7 has no CHAPTERS title/);
});

test('campaign: numeric order, the first unsolved is the frontier, chapters derive', () => {
  // this file registers l5 BEFORE l4 (card order) — the campaign must
  // order numerically anyway (the runtime unlock order regardless)
  assert.deepEqual(PioLevels.all(), ['l0', 'l1', 'l2', 'l3', 'l5', 'l4', 'l6', 'l7', 'l8']);
  assert.deepEqual(PioLevels.campaign(() => null).order, [
    'l0',
    'l1',
    'l2',
    'l3',
    'l4',
    'l5',
    'l6',
    'l7',
    'l8',
  ]);
  // fresh storage: nothing solved, the frontier is L0, no chapter complete
  const fresh = PioLevels.campaign(() => null);
  assert.equal(fresh.frontier, 'l0');
  assert.equal(fresh.solved.size, 0);
  assert.deepEqual(
    fresh.chapters.map((c) => c.complete),
    [false, false, false],
  );
  // a hermetic call (no read fn) is a fresh campaign
  assert.equal(PioLevels.campaign().frontier, 'l0');
  // mid-campaign: chapters 0–1 solved — frontier L6, both chapters ✓
  const mid = new Set(['l0', 'l1', 'l2', 'l3', 'l4', 'l5']);
  const midC = PioLevels.campaign((id) => (mid.has(id) ? { solved: true } : null));
  assert.equal(midC.frontier, 'l6');
  assert.deepEqual(
    midC.chapters.map((c) => c.complete),
    [true, true, false],
  );
  assert.deepEqual(
    midC.chapters.map((c) => c.levels),
    [
      ['l0', 'l1', 'l2'],
      ['l3', 'l4', 'l5'],
      ['l6', 'l7', 'l8'],
    ],
  );
  // non-contiguous solving does not skip: l0+l2 solved leaves the
  // frontier at l1 (furthest = max CONTIGUOUS solved)
  const gap = new Set(['l0', 'l2']);
  assert.equal(PioLevels.campaign((id) => (gap.has(id) ? { solved: true } : null)).frontier, 'l1');
  // all solved: no frontier, every chapter complete
  const done = PioLevels.campaign(() => ({ solved: true }));
  assert.equal(done.frontier, null);
  assert.deepEqual(
    done.chapters.map((c) => c.complete),
    [true, true, true],
  );
});

test('sessionKey is the spelling the level pages actually write', () => {
  assert.equal(PioLevels.sessionKey('l0'), 'vibe-pio-level-l0');
});

test('parText names its clock per judge kind — the band and the map agree', () => {
  assert.equal(PioLevels.parText(PioLevels.get('l1')), 'par 2 words · 8 clk/cycle');
  assert.equal(PioLevels.parText(PioLevels.get('l6')), 'par 2 words · 2 clk/bit');
  assert.equal(PioLevels.parText(PioLevels.get('l7')), 'par 3 words · 8 clk/bit');
  assert.equal(PioLevels.parText(PioLevels.get('l8')), 'par 4 words · 2 clk/bit');
});

// ============ C43: the transitions — the datum and the hop ============
// The solve datum (lvSession.solve: the passing listing + your axes)
// and the NEXT hop are module logic like the campaign derivation: the
// level page writes/reads them through these functions, the map reads
// them, and this gate pins the classification. Ran red first against
// the pre-C43 module: PioLevels.next was not a function.

test('next: the campaign-order successor, null at the last registered level', () => {
  assert.equal(PioLevels.next('l0'), 'l1');
  assert.equal(PioLevels.next('l5'), 'l6');
  assert.equal(PioLevels.next('l8'), null); // the last registered level hops to the map
  assert.equal(PioLevels.next('nope'), null); // unknown ids have no successor
});

test("programState assembles a given listing under the level's own context", () => {
  // the solved reload's boot: a session listing goes through the SAME
  // assembly path as a level file's (context, overlay, words)
  const ref = PioLevels.programState(L1, PioAsm, VibeDriver, L1.reference.listing);
  const yours = PioLevels.programState(L1, PioAsm, VibeDriver, [
    'set pins, 1 [3]',
    'set pins, 0 [3]',
  ]);
  assert.deepEqual(yours.words, ref.words); // the reference rows, bit-equal
  assert.deepEqual(yours.sms, ref.sms); // the config overlay is the level's, never the datum's
  // the default stays the BOOT listing — the datum is load-bearing, not
  // decorative (L1 boots un-slowed; the solve carries the [3] delays)
  const boot = PioLevels.programState(L1, PioAsm, VibeDriver);
  assert.notDeepEqual(boot.words, yours.words);
  // THE PAGE'S OWN SHAPE: levelPass stores ROWS.slice() — 32 rows with
  // '' tails. An '' row is untouched memory (word 0), never an assembly
  // error; the live session caught the first cut throwing on the tail
  // and the solved reload silently falling back to the boot listing.
  const asWritten = PioLevels.programState(L1, PioAsm, VibeDriver, [
    'set pins, 1 [3]',
    'set pins, 0 [3]',
    ...new Array(30).fill(''),
  ]);
  assert.deepEqual(asWritten.words, yours.words);
});

test('the solved session never re-locks the predict gate', () => {
  assert.equal(PioLevels.gateOpen(L0, {}), false); // the lock itself stands
  assert.equal(PioLevels.gateOpen(L0, { predicted: true }), true);
  // your own solution never re-locks: a solved session is past its
  // first run by construction (the C43 authored-programs rule whole)
  assert.equal(PioLevels.gateOpen(L0, { solved: true }), true);
});

test('youText/solveBadge: your axes beside par — matched, beaten, worse, the rx value axis', () => {
  // square: L1 par 2 words · 8 clk/cycle — the judge's period is the axis
  assert.equal(PioLevels.youText(L1, { words: 2, axis: 8 }), 'you 2·8');
  assert.equal(PioLevels.solveBadge(L1, { words: 2, axis: 8 }), 'matched');
  assert.equal(PioLevels.solveBadge(L1, { words: 1, axis: 8 }), 'beaten'); // cheaper at par time
  assert.equal(PioLevels.solveBadge(L1, { words: 2, axis: 9 }), null); // slower at par cost: honest no-badge
  assert.equal(PioLevels.solveBadge(L1, { words: 1, axis: 9 }), null); // cheaper AND slower: not Pareto-better
  assert.equal(PioLevels.solveBadge(L1, { words: 3, axis: 8 }), null); // dead rows cost words
  // uart: L7 par 3 words · 8 clk/bit — the measured frame/10 admits fractions
  assert.equal(PioLevels.youText(L7, { words: 3, axis: 8 }), 'you 3·8');
  assert.equal(PioLevels.youText(L7, { words: 3, axis: 8.4 }), 'you 3·8.4');
  assert.equal(PioLevels.solveBadge(L7, { words: 3, axis: 8 }), 'matched');
  assert.equal(PioLevels.solveBadge(L7, { words: 3, axis: 8.4 }), null); // relaxed-tier skew runs long
  assert.equal(PioLevels.solveBadge(L7, { words: 3, axis: 7.5 }), 'beaten');
  // rx: the value judge measures no clock (a value has no tolerance) —
  // words alone, the axis cell reads 'words' and never a bare number
  assert.equal(PioLevels.youText(L8, { words: 4, axis: null }), 'you 4 words');
  assert.equal(PioLevels.solveBadge(L8, { words: 4, axis: null }), 'matched');
  assert.equal(PioLevels.solveBadge(L8, { words: 3, axis: null }), 'beaten');
  assert.equal(PioLevels.solveBadge(L8, { words: 5, axis: null }), null);
  // no datum or garbage storage: nothing shows anywhere
  assert.equal(PioLevels.youText(L1, null), null);
  assert.equal(PioLevels.youText(L1, undefined), null);
  assert.equal(PioLevels.youText(L1, {}), null);
  assert.equal(PioLevels.youText(L1, { words: 'x', axis: 8 }), null);
  assert.equal(PioLevels.youText(L1, { words: 2 }), null); // a timing level without its measured clock is no datum
  assert.equal(PioLevels.solveBadge(L1, null), null);
  assert.equal(PioLevels.solveBadge(L1, { words: 2 }), null); // same rule on the badge
  assert.equal(PioLevels.solveBadge(L1, { words: 2, axis: 'x' }), null);
});
