// levels.test.js — the C34/C35 level-campaign gate (engine-side
// node --test, NOT a DOM-glue exception: it drives the level definitions
// against engine truth the way pio-asm-golden.json anchors the assembler).
//
// The engine truth arrives as committed golden pin series
// (web/tests/levels-golden.json, regenerated by tools/gen_level_goldens.py
// from pio_model — the same oracle make web's client gate runs against,
// bit-equal to the RTL). Every level under web/levels/ must:
//
//   - register a complete definition (id/name/chapter/goal, program,
//     panels, opcodes, profile, predict, reference+par) and assemble to
//     words bit-equal with pio_model's own assembler (the golden's words);
//   - carry only canonical listing rows (assemble∘disassemble = identity,
//     the C32 discipline) and an SM overlay that survives the C22
//     compose/decompose round-trip;
//   - PASS its own monitor profile over the reference golden series and
//     go RED over every perturbed golden (a judge that accepts the
//     perturbed waves is a lens pretending to be a judge);
//   - lock the transport behind the predict gate until a prediction is
//     committed — and never re-lock a re-run (the 2026-09-04 owner
//     decision: first run of a non-authored program only).
//
// The two standing defect hooks run their red/green demonstration
// in-process here (the TestMutationsDiverge idiom): {defect:'judge'}
// re-injects the single-glitch pass (stability ignored) and
// {defect:'gate'} re-injects the never-locks gate; the suite asserts the
// clean module is green AND that the very same checks diverge on the
// defective one.

'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const PioLevels = require('../levels.js');
const PioAsm = require('../pio-asm.js');
const VibeDriver = require('../engine-driver.js');
const GOLDEN = JSON.parse(fs.readFileSync(path.join(__dirname, 'levels-golden.json'), 'utf8'));

// the shipped level files register through the same hook the browser's
// classic scripts call (levels.js defines PIO_LEVEL; the loader document
// -writes the level file before sm-view.js evaluates)
globalThis.PIO_LEVEL = PioLevels.register;
require('../levels/l0.js');
require('../levels/l1.js');
require('../levels/l2.js');

const L0 = PioLevels.get('l0');
const G0 = GOLDEN.levels.l0;
const L1 = PioLevels.get('l1');
const G1 = GOLDEN.levels.l1;
const L2 = PioLevels.get('l2');
const G2 = GOLDEN.levels.l2;
const RowComplete = require('../row-complete.js');
const bits = (s) => [...s].map(Number);
const case_ = (name) => {
  const c = G0.cases.find((c) => c.name === name);
  assert.ok(c, `golden case ${name} exists`);
  return c;
};
const caseOf = (g, name) => {
  const c = g.cases.find((c) => c.name === name);
  assert.ok(c, `golden case ${name} exists`);
  return c;
};

// ---- the definition is complete and self-consistent ----------------------
test('l0 registers complete: identity, program, surface, profile, predict, par', () => {
  assert.equal(L0.id, 'l0');
  assert.equal(L0.name, 'First light');
  assert.equal(L0.chapter, 0);
  assert.equal(typeof L0.goal, 'string');
  assert.ok(L0.goal.length > 8, 'the goal is subgoal phrasing, not a letter');
  assert.ok(Array.isArray(L0.program.listing) && L0.program.listing.length > 0);
  assert.ok(Array.isArray(L0.program.sms) && L0.program.sms.length === 4);
  // the page IS the knowledge state: L0 shows transport+listing+wave only
  for (const key of ['transport', 'listing', 'wave']) assert.ok(L0.panels.includes(key));
  // no authoring in chapter 0 L0: the row-editor whitelist is empty
  assert.deepEqual(L0.opcodes, []);
  // the profile is versioned and tiered (the ladder's skeleton, C35 grows it)
  assert.equal(L0.profile.kind, 'square');
  assert.equal(L0.profile.v, 1);
  assert.ok(L0.profile.tiers[L0.profile.tier], 'the active tier is defined');
  // the predict gate: an answer that names one of the candidates
  assert.ok(L0.predict.candidates.some((c) => c.id === L0.predict.answer));
  assert.ok(L0.predict.candidates.every((c) => /^[01]+$/.test(c.bits)));
  assert.ok(L0.reference.par.words > 0 && L0.reference.par.period > 0);
});

test('every surface key maps to selectors that exist in the shipped page', () => {
  const html = fs.readFileSync(path.join(__dirname, '..', 'sm-view.html'), 'utf8');
  for (const [key, sels] of Object.entries(PioLevels.SURFACE)) {
    for (const sel of sels) {
      const m = sel.match(/^[.#]([A-Za-z0-9_-]+)$/);
      assert.ok(m, `surface ${key}: selector ${sel} must be one id/class`);
      const present = sel[0] === '#' ? html.includes(`id="${m[1]}"`) : html.includes(`${m[1]}`);
      assert.ok(present, `surface ${key}: ${sel} not found in sm-view.html`);
    }
  }
});

// ---- the program: canonical rows, pio_model-equal words, C22 overlay ------
test('l0 rows are canonical spellings: assemble(disassemble(w)) === w === the row', () => {
  const prog = PioAsm.createProgram('l0-check');
  prog.sidesetBits = 0; // no side-set in L0 (all five ds bits are delay)
  L0.program.listing.forEach((row) => {
    const w = PioAsm.assembleInstruction(row, prog, {}, `l0 row ${row}`);
    assert.equal(PioAsm.disassemble(w, false, 0), row, `${row} is not the canonical spelling`);
  });
});

test('l0 assembles to words bit-equal with the pio_model golden', () => {
  const st = PioLevels.programState(L0, PioAsm, VibeDriver);
  assert.deepEqual(st.words, G0.words);
  // a stored-program state the driver accepts as-is (parseState already ran)
  assert.equal(st.words.length, 32);
  assert.ok(
    st.words.slice(2).every((w) => w === 0),
    '32 rows, honest from cycle one',
  );
});

test('l0 SM overlay round-trips the C22 compose/decompose', () => {
  const st = PioLevels.programState(L0, PioAsm, VibeDriver);
  for (const group of ['clkdiv', 'pinctrl', 'execctrl', 'shiftctrl']) {
    const word = VibeDriver.composeOverlay(group, st.sms[0][group]);
    const back = VibeDriver.decomposeOverlay(group, word);
    for (const [field, v] of Object.entries(st.sms[0][group]))
      assert.deepEqual(back[field], v, `${group}.${field} survives compose∘decompose`);
    // the composed words equal the oracle's stim builders over the same
    // merged overlay (per SM — the disabled SMs compose their reset words)
    const gi = { pinctrl: 0, execctrl: 1, shiftctrl: 2, clkdiv: 3 }[group];
    for (let i = 0; i < 4; i++) {
      assert.equal(
        VibeDriver.composeOverlay(group, st.sms[i][group]),
        G0.config[i][gi],
        `SM${i} ${group} composes to the oracle word`,
      );
    }
  }
});

// ---- the judge: reference green, perturbed red ---------------------------
test('the square judge passes the reference golden — full series and windowed', () => {
  const ref = case_('reference');
  const full = PioLevels.judge(bits(ref.series), L0.profile);
  assert.equal(full.pass, true, full.verdict);
  assert.equal(full.period, 2); // set pins,1 / set pins,0: one clk each
  assert.equal(full.dutyPct, 50);
  // the browser judges the wave window (the driver's last-128 samples):
  // the verdict must not depend on where the window sits
  const win = PioLevels.judge(bits(ref.series).slice(-128), L0.profile);
  assert.equal(win.pass, true, win.verdict);
});

test('the square judge reds every perturbed golden, legibly', () => {
  for (const name of ['both-high', 'one-row', 'flat-low']) {
    const c = case_(name);
    const v = PioLevels.judge(bits(c.series), L0.profile);
    assert.equal(v.pass, false, `${name} must not pass its monitor profile`);
    assert.ok(v.verdict.length > 8, `${name} fails with a reason, not silence`);
  }
  // legibility spot-checks: the flat wave says the pin never rose
  assert.match(PioLevels.judge(bits(case_('flat-low').series), L0.profile).verdict, /never rose/);
});

test('{defect:judge} re-injects the single-glitch pass — clean red, defect green', () => {
  // one clean period, then the wave goes flat high: the clean judge needs
  // minPeriods steady cycles and stays red; the defect passes any single
  // in-range period (the lens masquerading as a judge)
  const blip = [0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1];
  const clean = PioLevels.judge(blip, L0.profile);
  const buggy = PioLevels.judge(blip, L0.profile, { judge: true });
  assert.equal(clean.pass, false, 'the clean judge refuses a one-period blip');
  assert.equal(buggy.pass, true, 'the defect hook passes it — divergence demonstrated');
  // and the clean judge still passes the real reference (green side)
  assert.equal(PioLevels.judge(bits(case_('reference').series), L0.profile).pass, true);
});

// ---- the predict gate ------------------------------------------------------
test('the gate locks the first run and never re-locks a re-run', () => {
  assert.equal(PioLevels.gateOpen(L0, {}), false, 'locked at boot: nothing predicted yet');
  assert.equal(PioLevels.gateOpen(L0, { predicted: true }), true, 'a commit opens it');
  // a reset re-runs the same program: the gate stays open (never punish
  // re-runs — the 2026-09-04 owner decision)
  assert.equal(PioLevels.gateOpen(L0, { predicted: true, solved: true }), true);
  // a level without a predict field (authored programs, later chapters)
  // never locks
  assert.equal(PioLevels.gateOpen({ ...L0, predict: null }, {}), true);
});

test('{defect:gate} re-injects the never-locks gate — divergence demonstrated', () => {
  const buggy = PioLevels.gateOpen(L0, {}, { gate: true });
  assert.equal(buggy, true, 'the defect ships the gate open');
  assert.equal(PioLevels.gateOpen(L0, {}), false, 'the clean gate locks at boot');
});

// ---- par dominates the reference on both axes ------------------------------
test('par dominates the reference solution on both axes', () => {
  const used = G0.words.filter((w) => w !== 0).length;
  assert.ok(used <= L0.reference.par.words, `${used} words > par ${L0.reference.par.words}`);
  const v = PioLevels.judge(bits(case_('reference').series), L0.profile);
  assert.ok(v.period <= L0.reference.par.period, `${v.period} clk/cycle > par period`);
});

// ---- C35: L1 Metronome — the delay column, the timing profile ---------------
// The fade's first rung: a one-cell modification. The program arrives as
// L0 left it; the monitor now TIMES it (the profile ladder's first real
// tier — exact period); the reference solution ships separately from the
// boot program for the first time.
test('l1 registers complete: delay column unlocked, exact-time profile, no gate', () => {
  assert.equal(L1.id, 'l1');
  assert.equal(L1.name, 'Metronome');
  assert.equal(L1.chapter, 0);
  assert.ok(L1.goal.length > 8);
  assert.ok(L1.panels.includes('delayCol'), "the delay column is L1's debut");
  assert.ok(!L1.panels.includes('sideCol'), 'no side column until chapter 4');
  // no authoring yet: the delay cell is the whole editor (the row editor
  // opens in a level for the first time in L2)
  assert.deepEqual(L1.opcodes, []);
  // the timing monitor is born: the active tier demands the exact period
  assert.equal(L1.profile.v, 1);
  assert.equal(L1.profile.tier, 'exact');
  assert.equal(L1.profile.tiers.exact.periodLo, 8);
  assert.equal(L1.profile.tiers.exact.periodHi, 8);
  // modify-from-given levels never lock the gate (only predict levels do)
  assert.equal(PioLevels.gateOpen(L1, {}), true);
  // the shipped answer, separate from the boot program
  assert.deepEqual(L1.reference.listing, ['set pins, 1 [3]', 'set pins, 0 [3]']);
  assert.ok(L1.reference.par.words > 0 && L1.reference.par.period > 0);
});

test('l2 registers complete: the empty boot, the set leash, the 1:3 target', () => {
  assert.equal(L2.id, 'l2');
  assert.equal(L2.name, "Author's hand");
  assert.equal(L2.chapter, 0);
  assert.ok(L2.goal.length > 8);
  // from scratch: the listing boots EMPTY — row-count honesty means the
  // player sees 32 honest `·` rows and writes into them
  assert.deepEqual(L2.program.listing, []);
  assert.ok(L2.panels.includes('delayCol'), 'the delay cell stays in scope');
  assert.ok(!L2.panels.includes('sideCol'), 'no side column until chapter 4');
  // the row editor opens in a level for the first time — on the leash
  assert.deepEqual(L2.opcodes, ['set']);
  assert.equal(L2.profile.v, 1);
  assert.equal(L2.profile.tier, 'exact');
  assert.equal(L2.profile.tiers.exact.periodLo, 4);
  assert.equal(L2.profile.tiers.exact.periodHi, 4);
  // the player authored the program from the first keystroke: no gate
  assert.equal(PioLevels.gateOpen(L2, {}), true);
  assert.deepEqual(L2.reference.listing, ['set pins, 1', 'set pins, 0 [2]']);
  assert.ok(L2.reference.par.words > 0 && L2.reference.par.period > 0);
});

test('l1/l2 reference listings are canonical spellings', () => {
  const prog = PioAsm.createProgram('c35-check');
  prog.sidesetBits = 0; // no side-set in chapter 0 (all five ds bits are delay)
  for (const L of [L1, L2])
    for (const row of L.reference.listing) {
      const w = PioAsm.assembleInstruction(row, prog, {}, `${L.id} reference ${row}`);
      assert.equal(PioAsm.disassemble(w, false, 0), row, `${row} is not the canonical spelling`);
    }
});

test('l1/l2 references assemble bit-equal with pio_model; the boots are their own words', () => {
  const prog = PioAsm.createProgram('c35-words');
  prog.sidesetBits = 0;
  for (const [L, G] of [
    [L1, G1],
    [L2, G2],
  ]) {
    const words = new Array(32).fill(0);
    L.reference.listing.forEach((row, i) => {
      words[i] = PioAsm.assembleInstruction(row, prog, {}, `${L.id} ref row ${i}`);
    });
    assert.deepEqual(words, G.words, `${L.id}: the JS assembler drifted from pio_model`);
    // the boot program is what the page loads (programState), and the
    // golden carries it separately whenever it differs from the reference
    const st = PioLevels.programState(L, PioAsm, VibeDriver);
    if (L.program.listing.join('|') !== L.reference.listing.join('|')) {
      assert.ok(G.boot, `${L.id}: the boot case is committed`);
      assert.deepEqual(st.words, G.boot.words, `${L.id}: the page boots the golden's boot words`);
    } else {
      assert.deepEqual(st.words, G.words);
    }
  }
  // L2 boots the empty machine: 32 untouched slots
  assert.ok(PioLevels.programState(L2, PioAsm, VibeDriver).words.every((w) => w === 0));
});

test('the metronome: the reference keeps exact time, every wrong time reds', () => {
  const ref = caseOf(G1, 'reference');
  const full = PioLevels.judge(bits(ref.series), L1.profile);
  assert.equal(full.pass, true, full.verdict);
  assert.equal(full.period, 8);
  assert.equal(full.dutyPct, 50);
  const win = PioLevels.judge(bits(ref.series).slice(-128), L1.profile);
  assert.equal(win.pass, true, win.verdict);
  // the boot program (as L0 left it) reds: the task is real from cycle one
  const boot = PioLevels.judge(bits(G1.boot.series), L1.profile);
  assert.equal(boot.pass, false);
  assert.match(boot.verdict, /outside/, 'the boot flash is timed, and legibly');
  // the wrong answers red with reasons
  for (const name of ['too-slow', 'lopsided', 'one-row']) {
    const c = caseOf(G1, name);
    const v = PioLevels.judge(bits(c.series), L1.profile);
    assert.equal(v.pass, false, `${name} must not pass the metronome`);
    assert.ok(v.verdict.length > 8, `${name} fails with a reason, not silence`);
  }
  // the near-miss is legible as a DUTY failure: period 8, duty 25
  assert.match(PioLevels.judge(bits(caseOf(G1, 'lopsided').series), L1.profile).verdict, /duty/);
});

test("the 1:3 target: the reference passes, last level's answer and the boot red", () => {
  const ref = caseOf(G2, 'reference');
  const full = PioLevels.judge(bits(ref.series), L2.profile);
  assert.equal(full.pass, true, full.verdict);
  assert.equal(full.period, 4);
  assert.equal(full.dutyPct, 25);
  assert.equal(PioLevels.judge(bits(ref.series).slice(-128), L2.profile).pass, true);
  // L1's solution is this level's red case: the target moved
  const l1a = PioLevels.judge(bits(caseOf(G2, 'l1-answer').series), L2.profile);
  assert.equal(l1a.pass, false);
  assert.match(l1a.verdict, /period/);
  // the opcode-locked attempt: nop cannot bring the pin low — the wave
  // rises once and holds
  const nop = PioLevels.judge(bits(caseOf(G2, 'nop-wait').series), L2.profile);
  assert.equal(nop.pass, false, 'the locked-opcode variant must not pass');
  // the empty boot never rises
  const boot = PioLevels.judge(bits(G2.boot.series), L2.profile);
  assert.equal(boot.pass, false);
  assert.match(boot.verdict, /never rose/);
});

// ---- C35: the editor's leash (the completion whitelist) ----------------------
// The row editor opens in a level for the first time in L2, scoped to the
// unlocked opcode set: a filter over C32's slot-aware candidates. The
// menu never suggests what the level has not unlocked — not at the
// mnemonic slot, and not inside a locked mnemonic's operand slots.
test('the leash: L2 completions scope to the unlocked opcode set', () => {
  const wl = { opcodes: L2.opcodes };
  assert.deepEqual(
    RowComplete.analyze('', wl).cands.map((c) => c.t),
    ['set'],
    'the mnemonic menu offers exactly the unlocked set',
  );
  assert.deepEqual(
    RowComplete.analyze('mo', wl).cands,
    [],
    'a locked mnemonic mid-word is never suggested',
  );
  assert.deepEqual(
    RowComplete.analyze('mov x', wl).cands,
    [],
    "a locked mnemonic's operand slots stay silent",
  );
  assert.deepEqual(
    RowComplete.analyze('', { opcodes: [] }).cands,
    [],
    "an empty whitelist offers nothing at all (L0's world)",
  );
  // the filter is load-bearing: unscoped, the menu offers all ten
  assert.deepEqual(
    RowComplete.analyze('').cands.map((c) => c.t),
    ['jmp', 'wait', 'in', 'out', 'push', 'pull', 'mov', 'irq', 'set', 'nop'],
  );
  // and the leash never touches the sandbox: no whitelist, full menu —
  // including set's own operand slots inside the whitelist
  assert.ok(RowComplete.analyze('set ', wl).cands.some((c) => c.t === 'pins'));
});

test('par dominates the l1/l2 reference solutions on both axes', () => {
  for (const [L, G] of [
    [L1, G1],
    [L2, G2],
  ]) {
    const used = G.words.filter((w) => w !== 0).length;
    assert.ok(used <= L.reference.par.words, `${L.id}: ${used} words > par`);
    const v = PioLevels.judge(bits(G.cases[0].series), L.profile);
    assert.ok(v.period <= L.reference.par.period, `${L.id}: ${v.period} clk/cycle > par`);
  }
});

// ---- C36: L3 Two ways to loop — jmp debuts with a job ----------------------
// Chapter 1 opens: a task wrap cannot do. The boot ships L2's answer
// transplanted after a once-preamble (row 0), and the pinned wrap
// (0..3) loops the WHOLE listing — the flash comes round every period,
// the exact tier reds it, and the only way out is a jmp back edge that
// skips row 0. The cost lesson is a golden: the naive jmp port of L2's
// rows runs one clk slower (period 5) — jmp eats a slot AND a cycle,
// wrap eats neither (the par line says 4 words · 4 clk; L2's par said
// the same wave in 2 words · 4 clk with no back-edge clk at all).
require('../levels/l3.js');
const L3 = PioLevels.get('l3');
const G3 = GOLDEN.levels.l3;

test('l3 registers complete: chapter 1, jmp on the leash, no gate', () => {
  assert.equal(L3.id, 'l3');
  assert.equal(L3.name, 'Two ways to loop');
  assert.equal(L3.chapter, 1);
  assert.ok(L3.goal.length > 8);
  // the boot: L2's answer after a once-preamble, wrap over the listing
  assert.deepEqual(L3.program.listing, ['set pins, 1 [7]', 'set pins, 1', 'set pins, 0 [2]']);
  assert.equal(L3.program.sms[0].execctrl.wrapTop, 3);
  assert.equal(L3.program.sms[0].execctrl.wrapBot, 0);
  assert.ok(L3.panels.includes('delayCol'), 'the delay cell stays in scope');
  assert.ok(!L3.panels.includes('sideCol'), 'no side column until chapter 4');
  assert.ok(!L3.panels.includes('wrapSteppers'), 'the wrap steppers stay locked');
  // the leash grows its first structural opcode: set + jmp, exactly
  assert.deepEqual(L3.opcodes, ['set', 'jmp']);
  // the same steady wave as L2 (the 1:3), judged at the exact tier
  assert.equal(L3.profile.v, 1);
  assert.equal(L3.profile.tier, 'exact');
  assert.equal(L3.profile.tiers.exact.periodLo, 4);
  assert.equal(L3.profile.tiers.exact.periodHi, 4);
  // modify-from-given: no predict card, the gate never locks
  assert.equal(PioLevels.gateOpen(L3, {}), true);
  // the shipped answer: preamble kept, jmp back edge, one delay shaved
  assert.deepEqual(L3.reference.listing, [
    'set pins, 1 [7]',
    'set pins, 1',
    'set pins, 0 [1]',
    'jmp 1',
  ]);
  assert.deepEqual(L3.reference.par, { words: 4, period: 4 });
});

test('the l3 leash: the menu offers set and jmp — the chapter-1 vocabulary', () => {
  const wl = { opcodes: L3.opcodes };
  assert.deepEqual(
    RowComplete.analyze('', wl).cands.map((c) => c.t),
    ['jmp', 'set'],
    'the mnemonic menu offers exactly the unlocked set (jmp first — the C32 order)',
  );
  // jmp's own slots stay live under the leash: digits are the target
  assert.ok(RowComplete.analyze('jm', wl).cands.some((c) => c.t === 'jmp'));
  assert.ok(RowComplete.analyze('jmp ', wl).cands.length >= 0, "jmp's target slot stays in play");
  // the still-locked majority stays silent
  assert.deepEqual(RowComplete.analyze('wa', wl).cands, []);
  assert.deepEqual(RowComplete.analyze('pull', wl).cands, []);
});

test('the l3 wave contract: boot reds (the wrap cannot skip row 0), reference greens', () => {
  // the boot: the whole-listing wrap re-runs the preamble — one long
  // flash every 13 clk, legibly outside the 4-clk window
  const boot = PioLevels.judge(bits(G3.boot.series), L3.profile);
  assert.equal(boot.pass, false);
  assert.match(boot.verdict, /period 13 .*outside/);
  // the reference: the steady 1:3 — full series and the wave window
  const ref = caseOf(G3, 'reference');
  const full = PioLevels.judge(bits(ref.series), L3.profile);
  assert.equal(full.pass, true, full.verdict);
  assert.equal(full.period, 4);
  assert.equal(full.dutyPct, 25);
  assert.equal(PioLevels.judge(bits(ref.series).slice(-128), L3.profile).pass, true);
  // the cost lesson, as a golden: the naive jmp port of L2's rows runs
  // one clk slower — jmp costs the cycle wrap does not
  const naive = PioLevels.judge(bits(caseOf(G3, 'jmp-cost').series), L3.profile);
  assert.equal(naive.pass, false);
  assert.match(naive.verdict, /period 5 .*outside/);
  // the wrong target: jmp 0 re-runs the preamble — structure, not syntax
  const j0 = PioLevels.judge(bits(caseOf(G3, 'jmp-target-0').series), L3.profile);
  assert.equal(j0.pass, false);
  assert.match(j0.verdict, /period 12 .*outside/);
});

test('l3 words are pio_model-equal and canonically spelled', () => {
  const prog = PioAsm.createProgram('c36-l3');
  prog.sidesetBits = 0;
  for (const row of [...L3.program.listing, ...L3.reference.listing]) {
    const w = PioAsm.assembleInstruction(row, prog, {}, `l3 row ${row}`);
    assert.equal(PioAsm.disassemble(w, false, 0), row, `${row} is not the canonical spelling`);
  }
  const st = PioLevels.programState(L3, PioAsm, VibeDriver);
  assert.deepEqual(st.words, G3.boot.words, 'the page boots the golden boot words');
  const words = new Array(32).fill(0);
  L3.reference.listing.forEach((row, i) => {
    words[i] = PioAsm.assembleInstruction(row, prog, {}, `l3 ref row ${i}`);
  });
  assert.deepEqual(words, G3.words, 'the reference assembles to the golden words');
});

// ---- C36: L5 The long blink — the [31] ceiling and the ds budget -----------
// The stretch level of chapter 1: the same 1:3 wave, sixteen times
// slower — high 16 of every 64 clk. No single row can wait 48 clk
// (SPEC-4-3's 5-bit budget), so the low time must split across rows;
// the wave window grows to see enough periods of the slow wave.
require('../levels/l5.js');
const L5 = PioLevels.get('l5');
const G5 = GOLDEN.levels.l5;

test('l5 registers complete: the long blink, the 512-sample window', () => {
  assert.equal(L5.id, 'l5');
  assert.equal(L5.name, 'The long blink');
  assert.equal(L5.chapter, 1);
  assert.ok(L5.goal.length > 8);
  // from scratch: the listing boots EMPTY
  assert.deepEqual(L5.program.listing, []);
  assert.equal(L5.program.sms[0].execctrl.wrapTop, 2);
  assert.equal(L5.program.sms[0].execctrl.wrapBot, 0);
  // the wave window: 64 clk/cycle needs 512 samples to hold the judge's
  // stability window (the level page is its own geometry — the sandbox
  // keeps 128)
  assert.equal(L5.waveWin, 512);
  // the chapter-1 vocabulary stays unlocked (knowledge is monotone)
  assert.deepEqual(L5.opcodes, ['set', 'jmp']);
  assert.equal(L5.profile.tier, 'exact');
  assert.equal(L5.profile.tiers.exact.periodLo, 64);
  assert.equal(L5.profile.tiers.exact.periodHi, 64);
  assert.equal(PioLevels.gateOpen(L5, {}), true);
  // the shipped answer: the 1:3 split — [15] / [31]+[15]
  assert.deepEqual(L5.reference.listing, [
    'set pins, 1 [15]',
    'set pins, 0 [31]',
    'set pins, 0 [15]',
  ]);
  assert.deepEqual(L5.reference.par, { words: 3, period: 64 });
});

test('the l5 wave contract: reference greens in both windows, near-misses red legibly', () => {
  const ref = caseOf(G5, 'reference');
  const full = PioLevels.judge(bits(ref.series), L5.profile);
  assert.equal(full.pass, true, full.verdict);
  assert.equal(full.period, 64);
  assert.equal(full.dutyPct, 25);
  // the browser judges the wave window — at 64 clk/cycle that window is
  // the level's own 512 samples, and the verdict must not depend on it
  assert.equal(PioLevels.judge(bits(ref.series).slice(-512), L5.profile).pass, true);
  // the empty boot never rises
  const boot = PioLevels.judge(bits(G5.boot.series), L5.profile);
  assert.equal(boot.pass, false);
  assert.match(boot.verdict, /never rose/);
  // the near-miss: one delay short of the split (period 63)
  const off1 = PioLevels.judge(bits(caseOf(G5, 'off-by-one').series), L5.profile);
  assert.equal(off1.pass, false);
  assert.match(off1.verdict, /period 63 .*outside/);
  // the forgotten third row: period 48
  assert.equal(PioLevels.judge(bits(caseOf(G5, 'one-row-short').series), L5.profile).pass, false);
  // both halves maxed at [31]: under the pinned wrap the two-row program
  // runs through the `·` row (a jmp 0 — it costs a clk), so period 65:
  // the empty row is not free, and the verdict says so
  const mx = PioLevels.judge(bits(caseOf(G5, 'both-maxed').series), L5.profile);
  assert.equal(mx.pass, false);
  assert.match(mx.verdict, /period 65 .*outside/);
});

test('l5 words are pio_model-equal and canonically spelled', () => {
  const prog = PioAsm.createProgram('c36-l5');
  prog.sidesetBits = 0;
  for (const row of L5.reference.listing) {
    const w = PioAsm.assembleInstruction(row, prog, {}, `l5 row ${row}`);
    assert.equal(PioAsm.disassemble(w, false, 0), row, `${row} is not the canonical spelling`);
  }
  assert.ok(PioLevels.programState(L5, PioAsm, VibeDriver).words.every((w) => w === 0));
  const words = new Array(32).fill(0);
  L5.reference.listing.forEach((row, i) => {
    words[i] = PioAsm.assembleInstruction(row, prog, {}, `l5 ref row ${i}`);
  });
  assert.deepEqual(words, G5.words, 'the reference assembles to the golden words');
});

// ---- C37: L4 Out of order — the scrambler (Parsons) -----------------------
// Comprehension by reordering: the rows arrive shuffled and the task is
// to trade them until the wave matches — zero generation load, the whole
// vocabulary is the given rows. The boot IS the canonical misconception:
// the once-flash ([7]) trapped inside the loop, so the flash comes round
// every period (period 14, legibly outside). The way out reads the jmp's
// semantics off the face: `jmp 1` names address 1, so the row at address
// 0 runs once — the flash belongs there. The second lesson ships as the
// high-before-jmp golden: the jmp's own clk holds the level of the row
// before it, so which row precedes the back edge is a real choice
// (duty 38, outside); and the dead-rows golden: rows after the jmp
// never execute at all.
require('../levels/l4.js');
const L4 = PioLevels.get('l4');
const G4 = GOLDEN.levels.l4;

test('l4 registers complete: the scramble flag, the permutation boot, no gate', () => {
  assert.equal(L4.id, 'l4');
  assert.equal(L4.name, 'Out of order');
  assert.equal(L4.chapter, 1);
  assert.ok(L4.goal.length > 8);
  // the scrambler posture: the listing gesture is the row trade — the
  // row editor never opens, the delay cell neither (the given rows are
  // fixed; only their addresses move)
  assert.equal(L4.scramble, true);
  // the boot is a true permutation of the reference: same rows, wrong
  // order (the player's whole move is reordering)
  assert.deepEqual([...L4.program.listing].sort(), [...L4.reference.listing].sort());
  assert.notDeepEqual(L4.program.listing, L4.reference.listing);
  // the jmp's target is part of the given vocabulary: address 1, the
  // loop entry the player must place a row at
  assert.ok(L4.program.listing.some((r) => /^jmp 1$/.test(r)));
  assert.ok(L4.panels.includes('delayCol'), 'reading [n] is the comprehension — the column stays');
  assert.ok(!L4.panels.includes('sideCol'), 'no side column until chapter 4');
  assert.ok(!L4.panels.includes('wrapSteppers'), 'the wrap steppers stay locked');
  // knowledge stays monotone (the chapter-1 vocabulary) even though the
  // scrambler never opens the editor the leash would scope
  assert.deepEqual(L4.opcodes, ['set', 'jmp']);
  // the same 8-clk 1:3 blink as the chapter's other levels, judged exact
  assert.equal(L4.profile.v, 1);
  assert.equal(L4.profile.tier, 'exact');
  assert.equal(L4.profile.tiers.exact.periodLo, 8);
  assert.equal(L4.profile.tiers.exact.periodHi, 8);
  // Parsons, not predict: the gate never locks
  assert.equal(PioLevels.gateOpen(L4, {}), true);
  // the shipped answer: the flash once, then the blink — the back edge
  // closes on a LOW row (the jmp's clk holds it)
  assert.deepEqual(L4.reference.listing, [
    'set pins, 1 [7]',
    'set pins, 1 [1]',
    'set pins, 0 [1]',
    'set pins, 0 [2]',
    'jmp 1',
  ]);
  assert.deepEqual(L4.reference.par, { words: 5, period: 8 });
});

test('the l4 wave contract: reference order green, the boot and planted wrong orders red', () => {
  // the boot: the flash trapped in the loop — it comes round every
  // period, legibly outside the 8-clk window
  const boot = PioLevels.judge(bits(G4.boot.series), L4.profile);
  assert.equal(boot.pass, false);
  assert.match(boot.verdict, /period 14 .*outside/);
  // the reference: flash once, then the 8-clk 1:3 blink — full series
  // and the wave window alike
  const ref = caseOf(G4, 'reference');
  const full = PioLevels.judge(bits(ref.series), L4.profile);
  assert.equal(full.pass, true, full.verdict);
  assert.equal(full.period, 8);
  assert.equal(full.dutyPct, 25);
  assert.equal(PioLevels.judge(bits(ref.series).slice(-128), L4.profile).pass, true);
  // the high row last: the jmp holds it — duty 38, the row before the
  // back edge is a real choice
  const hb = PioLevels.judge(bits(caseOf(G4, 'high-before-jmp').series), L4.profile);
  assert.equal(hb.pass, false);
  assert.match(hb.verdict, /duty 38% — outside/);
  // the jmp mid-listing: the rows after it never run — one flash, then
  // the wave goes flat (dead code is invisible to the monitor)
  const dead = PioLevels.judge(bits(caseOf(G4, 'dead-rows').series), L4.profile);
  assert.equal(dead.pass, false);
  assert.match(dead.verdict, /keep watching/);
});

test('l4 words are pio_model-equal, canonically spelled, and swap-equal', () => {
  const prog = PioAsm.createProgram('c37-l4');
  prog.sidesetBits = 0;
  for (const row of [...L4.program.listing, ...L4.reference.listing]) {
    const w = PioAsm.assembleInstruction(row, prog, {}, `l4 row ${row}`);
    assert.equal(PioAsm.disassemble(w, false, 0), row, `${row} is not the canonical spelling`);
  }
  // the page boots the golden's shuffled boot words
  const st = PioLevels.programState(L4, PioAsm, VibeDriver);
  assert.deepEqual(st.words, G4.boot.words);
  // a trade never adds or loses a word: boot and reference are the same
  // multiset of words, in different slots
  assert.deepEqual(
    [...st.words].sort((a, b) => a - b),
    [...G4.words].sort((a, b) => a - b),
  );
  const words = new Array(32).fill(0);
  L4.reference.listing.forEach((row, i) => {
    words[i] = PioAsm.assembleInstruction(row, prog, {}, `l4 ref row ${i}`);
  });
  assert.deepEqual(words, G4.words, 'the reference assembles to the golden words');
});

test('par dominates the l3/l4/l5 reference solutions on both axes', () => {
  for (const [L, G] of [
    [L3, G3],
    [L4, G4],
    [L5, G5],
  ]) {
    const used = G.words.filter((w) => w !== 0).length;
    assert.ok(used <= L.reference.par.words, `${L.id}: ${used} words > par`);
    const v = PioLevels.judge(bits(G.cases[0].series), L.profile);
    assert.ok(v.period <= L.reference.par.period, `${L.id}: ${v.period} clk/cycle > par`);
  }
});
