// pio-asm.test.js — the C19 golden-vector + round-trip suite for the
// in-browser assembler/disassembler (KANBAN C19).
//
// web/pio-asm.js is a JS port of the C12 pio_model asm/disasm/encoding
// trio. A port could be *consistently* wrong (assemble and disassemble
// agreeing with each other but not with the hardware), so the port is
// anchored to pio_model — which is itself bit-equal to pioasm 2.3.0 on
// every conformance program (difftest --asm-check) — through the
// committed fixture pio-asm-golden.json (generated by
// tools/gen_pio_asm_golden.py; `make js` re-checks it for drift):
//
//   - golden words:  assembling each conformance .pio source must
//                    reproduce pio_model's (pioasm-equal) words;
//   - golden text:   disassembling each word under the program's own
//                    side-set config must reproduce pio_model's
//                    canonical text;
//   - golden exprs:  the expression evaluator pins the C
//                    truncating-division corners a naive JS `/`/`%`
//                    port gets wrong;
//   - round-trip:    the C12 1-1 property, ported whole — every one of
//                    the 65536 words, under 4 side-set configs, must
//                    satisfy assemble(disassemble(w)) === w (reserved
//                    encodings have no faithful text and are skipped —
//                    exactly the difftest --asm-check loop).

'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const PioAsm = require('../pio-asm.js');

const golden = JSON.parse(fs.readFileSync(path.join(__dirname, 'pio-asm-golden.json'), 'utf8'));

// ---- golden words + golden canonical text --------------------------------
for (const g of golden.programs) {
  test(`golden ${g.name}: assemble == pio_model words, disasm == canonical text`, () => {
    const progs = PioAsm.parseText(g.src, `${g.name}.pio`);
    const p = progs.find((q) => q.name === g.name);
    assert.ok(p, `program ${g.name} not parsed`);
    assert.equal(p.sidesetBits, g.sideset.bits);
    assert.equal(p.sidesetOpt, g.sideset.opt);
    assert.deepEqual(p.words, g.words);
    const sideEn = g.sideset.bits !== null && g.sideset.opt;
    const ssCount = g.sideset.bits === null ? 0 : g.sideset.bits + (g.sideset.opt ? 1 : 0);
    g.words.forEach((w, i) => {
      assert.equal(
        PioAsm.disassemble(w, sideEn, ssCount),
        g.disasm[i],
        `word ${i} (0x${w.toString(16)})`,
      );
    });
  });
}

// ---- golden expressions (the C-division corners) --------------------------
test('golden exprs: evaluator matches pio_model (C truncating division)', () => {
  for (const e of golden.exprs) {
    assert.equal(PioAsm.evalExpr(e.text, e.symbols), e.value, e.text);
  }
});

// ---- the C12 1-1 round-trip property, ported whole ------------------------
// assemble(disassemble(w)) === w for every word under 4 side-set configs
// (the difftest --asm-check loop; reserved encodings are skipped — they
// have no faithful text).
test('round-trip: canonical disassembly re-assembles bit-identically (4 cfgs x 65536 words)', () => {
  const cfgs = [
    [false, 0],
    [false, 2],
    [true, 2],
    [true, 3],
  ];
  let checked = 0;
  let reserved = 0;
  for (const [sideEn, ss] of cfgs) {
    const prog = PioAsm.createProgram('rt');
    prog.sidesetBits = ss - (sideEn ? 1 : 0);
    prog.sidesetOpt = sideEn;
    for (let w = 0; w < 0x10000; w++) {
      let txt;
      try {
        txt = PioAsm.disassemble(w, sideEn, ss);
      } catch (e) {
        if (e instanceof PioAsm.ReservedEncoding) {
          reserved++;
          continue;
        }
        throw e;
      }
      const w2 = PioAsm.assembleInstruction(txt, prog, {}, 'rt');
      assert.equal(w2, w, `0x${w.toString(16)} -> "${txt}" -> 0x${w2.toString(16)}`);
      checked++;
    }
  }
  // The canonical/reserved partition is pinned to the oracle: pio_model
  // counts 42048+42048+31536+26280 = 141912 canonical words over these
  // four configs (reserved encodings have no faithful text). A port that
  // disagrees about WHICH words are canonical shifts this total.
  assert.equal(checked, 141912);
  assert.ok(reserved > 0, 'no reserved encodings seen — the skip path is dead');
});

// ---- encoding surface (mirrors tests/test_encoding.py pins) ---------------
test('encoding: field split, known words, count-0 => 32', () => {
  assert.deepEqual(PioAsm.split(0xa042), [PioAsm.C_MOV, 0, 2, 2]);
  assert.equal(PioAsm.encodeJmp(null, 0, 0), 0x0000);
  assert.equal(PioAsm.encodeMov('y', 'y', PioAsm.MOP_NONE, 0), 0xa042); // nop
  assert.equal(PioAsm.encodeSet('pins', 1, 0), 0xe001);
  assert.equal(PioAsm.encodeOut('pins', 1, 0), 0x6001);
  assert.equal(PioAsm.encodeIn('pins', 8, 0), 0x4008);
  assert.equal(PioAsm.encodePush(false, true, 0), 0x8020);
  assert.equal(PioAsm.decode(PioAsm.encodeIn('x', 0, 0)).in_count, 32); // SPEC-2-18
  assert.equal(PioAsm.encodePut(null, 0) & 0x1f, 0x10); // SPEC-2-12 index packing
  assert.equal(PioAsm.encodePut(2, 0) & 0x1f, 0x1a);
});

test('encoding: reserved decodes are flagged, not thrown (SPEC-13-1)', () => {
  assert.equal(PioAsm.decode(PioAsm.encodeIn('pins', 0, 0) | (4 << 5)).illegal, true);
  assert.equal(PioAsm.decode(PioAsm.encodeMov('x', 'x', 3, 0)).illegal, true);
  assert.equal(PioAsm.decode(PioAsm.encodeIrq(true, true, null, 0, 0)).illegal, true);
  assert.equal(PioAsm.decode(PioAsm.encode(PioAsm.C_SET, 3, 0, 0)).illegal, true);
});

test('encoding: sideset split under opt (SPEC-4-1..3)', () => {
  assert.deepEqual(PioAsm.splitSideset(0b11010, true, 2), {
    delay: 2,
    ssValid: true,
    ssVal: 1,
    ssBits: 1,
  });
  assert.deepEqual(PioAsm.splitSideset(0b01010, true, 2), {
    delay: 2,
    ssValid: false,
    ssVal: 0,
    ssBits: 0,
  });
  assert.deepEqual(PioAsm.splitSideset(0b10111, false, 3), {
    delay: 3,
    ssValid: true,
    ssVal: 5,
    ssBits: 3,
  });
});

// ---- directives + program metadata (mirrors tests/test_asm.py pins) -------
test('directives: wrap bounds, defines, labels, %% blocks, defaults', () => {
  const p = PioAsm.parseText('.program t\n.wrap_target\nnop\nnop\n.wrap\nnop\n')[0];
  assert.equal(p.wrap, 1);
  assert.equal(p.wrapTarget, 0);

  const d = PioAsm.parseText('.program t\n.define public N 3\nset x, N\n')[0];
  assert.equal(d.words[0], PioAsm.encodeSet('x', 3, 0));
  assert.equal(d.symbols.N, 3);
  assert.ok(d.publicSymbols.has('N'));

  const l = PioAsm.parseText('.program t\npublic loop:\nnop\njmp loop\n')[0];
  assert.equal(l.labels.loop, 0);
  assert.ok(l.publicLabels.has('loop'));
  assert.equal(l.words[1], PioAsm.encodeJmp(null, 0, 0));

  const b = PioAsm.parseText('.program t\n.lang_opt c func=1\n% c-sdk {\nnot parsed\n%}\nnop\n')[0];
  assert.deepEqual(b.words, [0xa042]);

  const single = PioAsm.parseText('.program t\nset pins, 1\n')[0];
  assert.equal(single.wrap, 0); // single instruction: bounds collapse
  assert.equal(single.wrapTarget, 0);

  const v = PioAsm.parseText('.pio_version 1\n.program t\nnop\n')[0];
  assert.equal(v.pioVersion, 1);

  const s = PioAsm.parseText('.program t\n.side_set 1 opt\nout pins, 1 side 1 [2]\n')[0];
  assert.equal(s.sidesetBits, 1);
  assert.ok(s.sidesetOpt);
  assert.equal(s.sidesetCount, 2); // incl. enable bit (SPEC-7-26)
  assert.equal(s.words[0], 0x6001 | (0x1a << 8)); // SPEC-4-2/4-3
});

// ---- errors: AsmError / ReservedEncoding (mirrors the Python suite) -------
test('errors: asm errors name the source line', () => {
  assert.throws(() => PioAsm.parseText('nop\n'), PioAsm.AsmError); // outside .program
  assert.throws(() => PioAsm.parseText('.program t\nfrobnicate x\n'), PioAsm.AsmError);
  assert.throws(() => PioAsm.parseText('.program t\nx: nop\nx: nop\n'), PioAsm.AsmError);
  assert.throws(() => PioAsm.parseText('.program t\nirq clear\n'), /irq needs an index/);
  assert.throws(() => PioAsm.parseText('.program t\n.fifo 8\nnop\n'), PioAsm.AsmError);
  assert.throws(() => PioAsm.parseText('.program t\n.bogus 1\nnop\n'), PioAsm.AsmError);
  assert.throws(() => PioAsm.evalExpr('1/0', {}), PioAsm.AsmError);
  assert.throws(() => PioAsm.evalExpr('nope', {}), PioAsm.AsmError);
  assert.throws(() => PioAsm.evalExpr('1 + $', {}), PioAsm.AsmError);
  // unknown operand reaches AsmError, not a raw undefined key
  assert.throws(() => PioAsm.parseText('.program t\nin bogus, 1\n'), PioAsm.AsmError);
});

test('errors: reserved encodings raise on disassembly (SPEC-13-1)', () => {
  assert.throws(
    () => PioAsm.disassemble(PioAsm.encodeIn('pins', 0, 0) | (4 << 5)),
    PioAsm.ReservedEncoding,
  );
  assert.throws(
    () => PioAsm.disassemble(PioAsm.encodeSet('pins', 0, 0) | (3 << 5)),
    PioAsm.ReservedEncoding,
  ); // SET dst 3
  // aliased ds field: opt enable 0 but data bits set (SPEC-4-1..3)
  assert.throws(() => PioAsm.disassemble(0x8020 | (0x08 << 8), true, 2), PioAsm.ReservedEncoding);
  // side value with SIDESET_COUNT=0 cannot be packed (SPEC-4-9)
  assert.throws(() => PioAsm.packDs(0, 1, false, 0, true), PioAsm.ReservedEncoding);
});
